package com.distribution.modules.card.entity;

import lombok.Data;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table card_info
 *
 * @mbg.generated do_not_delete_during_merge
 */
@Data
public class CardInfo {
    /** */
    private String id;

    /** 银行代号*/
    private String bankNum;

    /** 信用卡代号*/
    private String cardNum;

    /** 信用卡名称*/
    private String cardName;

    /** 信用卡图片*/
    private String cardImg;

    /** 信用卡详情*/
    private String cardInfo;

    /** 信用卡办理链接*/
    private String cardUrl;

    /** */
    private String updateTime;

    /** */
    private String addTime;

    /** */
    private String isDelete;
    /**
     * 佣金返利
     */
    private Double rebate;
}