package com.distribution.modules.memeber.dao;

import com.distribution.modules.memeber.entity.MemeberInfo;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;
import java.util.Map;

@Mapper
public interface MemeberInfoMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table card_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * 批量删除
     * @param ids
     * @return
     */
    int deleteBatch(String[] ids);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table card_info
     *
     * @mbg.generated
     */
    int insert(MemeberInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table card_info
     *
     * @mbg.generated
     */
    int insertSelective(MemeberInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table card_info
     *
     * @mbg.generated
     */
    MemeberInfo selectByPrimaryKey(String id);

    /**
     * 查询列表
     * @param param
     * @return
     */
    List<MemeberInfo> selectList(Map<String, Object> param);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table card_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MemeberInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table card_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MemeberInfo record);
}
