# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
    port-header: X-Forwarded-Port
    protocol-header: x-forwarded-proto
    remote-ip-header: x-forwarded-for
  port: 8088
  use-forward-headers: true
  connection-timeout: 5000ms
  servlet:
    context-path: /dis

# mysql
spring:
  application:
    name: dis
  # 环境 dev|test|pro
  profiles:
    #        active: pro
    active: dev
  #    datasource:
  #        type: com.alibaba.druid.pool.DruidDataSource
  #        driverClassName: com.mysql.jdbc.Driver
  #    activiti:
  #      check-process-definitions: false
  # jackson时间格式化
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
  # 指定静态资源的路径
  resources:
    static-locations: classpath:/static/,classpath:/views/,file:${risk.file-path}
  redis:
    #        open: true  # 是否开启redis缓存  true开启   false关闭
    database: 0
    host: localhost
    port: 6379
    password:       # 密码（默认为空）
    timeout: 6000ms  # 连接超时时长（毫秒）
    jedis:
      pool:
        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 5       # 连接池中的最小空闲连接
  devtools:
    livereload:
      enabled: true
    restart:
      exclude: views/**,static/**
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    publisher-confirms: true #开启发送确认
    publisher-returns: true #开启发送失败退回
    listener:
      simple:
        acknowledge-mode: manual
        retry:
          enabled: true


jetcache:
  statIntervalMinutes: 15
  areaInCacheName: false
  local:
    default:
      type: caffeine
      keyConvertor: fastjson
  remote:
    default:
      type: redis.lettuce
      keyConvertor: fastjson
      uri: redis://127.0.0.1:6379/


# Mybatis配置
mybatis:
  mapperLocations: classpath:mapper/**/*.xml
  #    configLocation: classpath:mybatis.xml
  configuration:
    map-underscore-to-camel-case: true

#mybatis分页
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql


