package com.distribution.modules.dis.entity

import java.io.Serializable

/**
 * 分润设置实体类
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table dis_profi_param
 *
 * @mbg.generated do_not_delete_during_merge
 */

data class DisProfiParam(
        private val serialVersionUID: Long = 1L,
        /**  */
        var id: String = "",

        /**
         * 平台id
         */
        var disPlatformId: String = "",

        /**
         * 分润模型，如 百分比和固定金额
         */
        var disProMode: String = "",

        /**
         * 分润类别，如上级发展下级分润 ，交易分润。。。。
         */
        var disProType: String = "",

        /**
         * 分润值
         */
        var disProValue: Double = 0.00,

        /**
         * 从下往上对应的级别关系
         */
        var disProLevel: String = "",


        /**
         * 会员类型（0:非会员 1：会员）
         */
        var disUserType: String = "",


        /**  */
        var isDelete: String = "",


        /**  */
        var updateTime: String = "",


        /**  */
        var addTime: String = ""

) : Serializable