package com.distribution.modules.dis.entity

import com.distribution.common.utils.DateUtils
import java.math.BigDecimal
import java.time.LocalDateTime

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table dis_profit_record
 *
 * @mbg.generated do_not_delete_during_merge
 */

data class DisProfitRecord(
        /**  */
        var id: String = "",

        /**  */
        var disPlatformId:String = "1",


        /**  */
        var disGetUserId: String = "",

        /**  */
        var disSetUserId: String = "",


        /**  */
        var disAmount: BigDecimal = BigDecimal.ZERO,


        /**
         * 交易类型
         */
        var disProType: String = "",


        /**
         * 备注
         */
        var disNote: String = "",


        /**  */
        var account: String = "",


        /**
         * 对应第三方订单编号
         */
        var disOrderId: String = "",


        /**  */
        var isDelete:String = "1",

        /**  */
        var addTime: String =  DateUtils.formatDateTime(LocalDateTime.now()),


        /**  */
        var updateTime: String =  DateUtils.formatDateTime(LocalDateTime.now())
                                    
)