package com.distribution.modules.dis.dao

import com.distribution.modules.dis.entity.DisProfitRecord
import org.apache.ibatis.annotations.Mapper

@Mapper
interface DisProfitRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_profit_record
     *
     * @mbg.generated
     */
    fun deleteByPrimaryKey(id: String): Int

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_profit_record
     *
     * @mbg.generated
     */
    fun insert(record: DisProfitRecord): Int

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_profit_record
     *
     * @mbg.generated
     */
    fun insertSelective(record: DisProfitRecord): Int

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_profit_record
     *
     * @mbg.generated
     */
    fun selectByPrimaryKey(id: String): DisProfitRecord

    fun selectList(param: Map<*, *>): List<DisProfitRecord>

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_profit_record
     *
     * @mbg.generated
     */
    fun updateByPrimaryKeySelective(record: DisProfitRecord): Int

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dis_profit_record
     *
     * @mbg.generated
     */
    fun updateByPrimaryKey(record: DisProfitRecord): Int
}