/*
 * This file is generated by jOOQ.
*/
package com.distribution.pojo.tables.records;


import com.distribution.pojo.tables.DisFans;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 锁粉表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DisFansRecord extends UpdatableRecordImpl<DisFansRecord> implements Record6<String, String, String, String, String, Long> {

    private static final long serialVersionUID = -1674209583;

    /**
     * Setter for <code>distribution.dis_fans.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>distribution.dis_fans.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>distribution.dis_fans.member_id</code>. 关联的推荐人ID
     */
    public void setMemberId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>distribution.dis_fans.member_id</code>. 关联的推荐人ID
     */
    public String getMemberId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>distribution.dis_fans.wechat_id</code>. 微信ID
     */
    public void setWechatId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>distribution.dis_fans.wechat_id</code>. 微信ID
     */
    public String getWechatId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>distribution.dis_fans.wechat_img</code>. 微信头像
     */
    public void setWechatImg(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>distribution.dis_fans.wechat_img</code>. 微信头像
     */
    public String getWechatImg() {
        return (String) get(3);
    }

    /**
     * Setter for <code>distribution.dis_fans.wechat_nickname</code>. 微信昵称
     */
    public void setWechatNickname(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>distribution.dis_fans.wechat_nickname</code>. 微信昵称
     */
    public String getWechatNickname() {
        return (String) get(4);
    }

    /**
     * Setter for <code>distribution.dis_fans.worker_id</code>. 工号
     */
    public void setWorkerId(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>distribution.dis_fans.worker_id</code>. 工号
     */
    public Long getWorkerId() {
        return (Long) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<String, String, String, String, String, Long> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<String, String, String, String, String, Long> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return DisFans.DIS_FANS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return DisFans.DIS_FANS.MEMBER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return DisFans.DIS_FANS.WECHAT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return DisFans.DIS_FANS.WECHAT_IMG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return DisFans.DIS_FANS.WECHAT_NICKNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field6() {
        return DisFans.DIS_FANS.WORKER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getMemberId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getWechatId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getWechatImg();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getWechatNickname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component6() {
        return getWorkerId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getMemberId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getWechatId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getWechatImg();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getWechatNickname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value6() {
        return getWorkerId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DisFansRecord value1(String value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DisFansRecord value2(String value) {
        setMemberId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DisFansRecord value3(String value) {
        setWechatId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DisFansRecord value4(String value) {
        setWechatImg(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DisFansRecord value5(String value) {
        setWechatNickname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DisFansRecord value6(Long value) {
        setWorkerId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DisFansRecord values(String value1, String value2, String value3, String value4, String value5, Long value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DisFansRecord
     */
    public DisFansRecord() {
        super(DisFans.DIS_FANS);
    }

    /**
     * Create a detached, initialised DisFansRecord
     */
    public DisFansRecord(String id, String memberId, String wechatId, String wechatImg, String wechatNickname, Long workerId) {
        super(DisFans.DIS_FANS);

        set(0, id);
        set(1, memberId);
        set(2, wechatId);
        set(3, wechatImg);
        set(4, wechatNickname);
        set(5, workerId);
    }
}
