/*
 * This file is generated by jOOQ.
*/
package com.distribution.pojo.tables.records;


import com.distribution.pojo.tables.DisProfitRecord;

import java.math.BigDecimal;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record12;
import org.jooq.Row12;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 分润记录表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DisProfitRecordRecord extends UpdatableRecordImpl<DisProfitRecordRecord> implements Record12<String, String, String, String, BigDecimal, String, String, String, String, String, String, String> {

    private static final long serialVersionUID = 1803550922;

    /**
     * Setter for <code>distribution_dev.dis_profit_record.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>distribution_dev.dis_profit_record.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>distribution_dev.dis_profit_record.dis_platform_id</code>.
     */
    public void setDisPlatformId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>distribution_dev.dis_profit_record.dis_platform_id</code>.
     */
    public String getDisPlatformId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>distribution_dev.dis_profit_record.dis_get_user_id</code>.
     */
    public void setDisGetUserId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>distribution_dev.dis_profit_record.dis_get_user_id</code>.
     */
    public String getDisGetUserId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>distribution_dev.dis_profit_record.dis_set_user_id</code>.
     */
    public void setDisSetUserId(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>distribution_dev.dis_profit_record.dis_set_user_id</code>.
     */
    public String getDisSetUserId() {
        return (String) get(3);
    }

    /**
     * Setter for <code>distribution_dev.dis_profit_record.dis_amount</code>.
     */
    public void setDisAmount(BigDecimal value) {
        set(4, value);
    }

    /**
     * Getter for <code>distribution_dev.dis_profit_record.dis_amount</code>.
     */
    public BigDecimal getDisAmount() {
        return (BigDecimal) get(4);
    }

    /**
     * Setter for <code>distribution_dev.dis_profit_record.dis_pro_type</code>. 交易类型
     */
    public void setDisProType(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>distribution_dev.dis_profit_record.dis_pro_type</code>. 交易类型
     */
    public String getDisProType() {
        return (String) get(5);
    }

    /**
     * Setter for <code>distribution_dev.dis_profit_record.dis_note</code>. 备注
     */
    public void setDisNote(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>distribution_dev.dis_profit_record.dis_note</code>. 备注
     */
    public String getDisNote() {
        return (String) get(6);
    }

    /**
     * Setter for <code>distribution_dev.dis_profit_record.account</code>. 账号
     */
    public void setAccount(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>distribution_dev.dis_profit_record.account</code>. 账号
     */
    public String getAccount() {
        return (String) get(7);
    }

    /**
     * Setter for <code>distribution_dev.dis_profit_record.dis_order_id</code>. 对应第三方订单编号
     */
    public void setDisOrderId(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>distribution_dev.dis_profit_record.dis_order_id</code>. 对应第三方订单编号
     */
    public String getDisOrderId() {
        return (String) get(8);
    }

    /**
     * Setter for <code>distribution_dev.dis_profit_record.is_delete</code>.
     */
    public void setIsDelete(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>distribution_dev.dis_profit_record.is_delete</code>.
     */
    public String getIsDelete() {
        return (String) get(9);
    }

    /**
     * Setter for <code>distribution_dev.dis_profit_record.add_time</code>.
     */
    public void setAddTime(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>distribution_dev.dis_profit_record.add_time</code>.
     */
    public String getAddTime() {
        return (String) get(10);
    }

    /**
     * Setter for <code>distribution_dev.dis_profit_record.update_time</code>.
     */
    public void setUpdateTime(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>distribution_dev.dis_profit_record.update_time</code>.
     */
    public String getUpdateTime() {
        return (String) get(11);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record12 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row12<String, String, String, String, BigDecimal, String, String, String, String, String, String, String> fieldsRow() {
        return (Row12) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row12<String, String, String, String, BigDecimal, String, String, String, String, String, String, String> valuesRow() {
        return (Row12) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return DisProfitRecord.DIS_PROFIT_RECORD.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return DisProfitRecord.DIS_PROFIT_RECORD.DIS_PLATFORM_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return DisProfitRecord.DIS_PROFIT_RECORD.DIS_GET_USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return DisProfitRecord.DIS_PROFIT_RECORD.DIS_SET_USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field5() {
        return DisProfitRecord.DIS_PROFIT_RECORD.DIS_AMOUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return DisProfitRecord.DIS_PROFIT_RECORD.DIS_PRO_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return DisProfitRecord.DIS_PROFIT_RECORD.DIS_NOTE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return DisProfitRecord.DIS_PROFIT_RECORD.ACCOUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return DisProfitRecord.DIS_PROFIT_RECORD.DIS_ORDER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return DisProfitRecord.DIS_PROFIT_RECORD.IS_DELETE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return DisProfitRecord.DIS_PROFIT_RECORD.ADD_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field12() {
        return DisProfitRecord.DIS_PROFIT_RECORD.UPDATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getDisPlatformId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getDisGetUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getDisSetUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component5() {
        return getDisAmount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getDisProType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getDisNote();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getAccount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getDisOrderId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component10() {
        return getIsDelete();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component11() {
        return getAddTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component12() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getDisPlatformId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getDisGetUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getDisSetUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value5() {
        return getDisAmount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getDisProType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getDisNote();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getAccount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getDisOrderId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getIsDelete();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getAddTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value12() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DisProfitRecordRecord value1(String value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DisProfitRecordRecord value2(String value) {
        setDisPlatformId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DisProfitRecordRecord value3(String value) {
        setDisGetUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DisProfitRecordRecord value4(String value) {
        setDisSetUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DisProfitRecordRecord value5(BigDecimal value) {
        setDisAmount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DisProfitRecordRecord value6(String value) {
        setDisProType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DisProfitRecordRecord value7(String value) {
        setDisNote(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DisProfitRecordRecord value8(String value) {
        setAccount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DisProfitRecordRecord value9(String value) {
        setDisOrderId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DisProfitRecordRecord value10(String value) {
        setIsDelete(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DisProfitRecordRecord value11(String value) {
        setAddTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DisProfitRecordRecord value12(String value) {
        setUpdateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DisProfitRecordRecord values(String value1, String value2, String value3, String value4, BigDecimal value5, String value6, String value7, String value8, String value9, String value10, String value11, String value12) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DisProfitRecordRecord
     */
    public DisProfitRecordRecord() {
        super(DisProfitRecord.DIS_PROFIT_RECORD);
    }

    /**
     * Create a detached, initialised DisProfitRecordRecord
     */
    public DisProfitRecordRecord(String id, String disPlatformId, String disGetUserId, String disSetUserId, BigDecimal disAmount, String disProType, String disNote, String account, String disOrderId, String isDelete, String addTime, String updateTime) {
        super(DisProfitRecord.DIS_PROFIT_RECORD);

        set(0, id);
        set(1, disPlatformId);
        set(2, disGetUserId);
        set(3, disSetUserId);
        set(4, disAmount);
        set(5, disProType);
        set(6, disNote);
        set(7, account);
        set(8, disOrderId);
        set(9, isDelete);
        set(10, addTime);
        set(11, updateTime);
    }
}
