/*
 * This file is generated by jOOQ.
*/
package com.distribution.pojo.tables.records;


import com.distribution.pojo.tables.DisProfiParam;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 分润参数设置
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DisProfiParamRecord extends UpdatableRecordImpl<DisProfiParamRecord> implements Record10<String, String, String, String, Double, String, String, String, String, String> {

    private static final long serialVersionUID = 1409454856;

    /**
     * Setter for <code>distribution.dis_profi_param.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>distribution.dis_profi_param.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>distribution.dis_profi_param.dis_platform_id</code>. 平台id
     */
    public void setDisPlatformId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>distribution.dis_profi_param.dis_platform_id</code>. 平台id
     */
    public String getDisPlatformId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>distribution.dis_profi_param.dis_pro_mode</code>. 分润模型，如 百分比和固定金额
     */
    public void setDisProMode(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>distribution.dis_profi_param.dis_pro_mode</code>. 分润模型，如 百分比和固定金额
     */
    public String getDisProMode() {
        return (String) get(2);
    }

    /**
     * Setter for <code>distribution.dis_profi_param.dis_pro_type</code>. 分润类别，如上级发展下级分润 ，交易分润。。。。
     */
    public void setDisProType(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>distribution.dis_profi_param.dis_pro_type</code>. 分润类别，如上级发展下级分润 ，交易分润。。。。
     */
    public String getDisProType() {
        return (String) get(3);
    }

    /**
     * Setter for <code>distribution.dis_profi_param.dis_pro_value</code>. 分润值
     */
    public void setDisProValue(Double value) {
        set(4, value);
    }

    /**
     * Getter for <code>distribution.dis_profi_param.dis_pro_value</code>. 分润值
     */
    public Double getDisProValue() {
        return (Double) get(4);
    }

    /**
     * Setter for <code>distribution.dis_profi_param.dis_pro_level</code>. 从下往上对应的级别关系
     */
    public void setDisProLevel(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>distribution.dis_profi_param.dis_pro_level</code>. 从下往上对应的级别关系
     */
    public String getDisProLevel() {
        return (String) get(5);
    }

    /**
     * Setter for <code>distribution.dis_profi_param.dis_user_type</code>. 会员类型（0:非会员 1：会员）
     */
    public void setDisUserType(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>distribution.dis_profi_param.dis_user_type</code>. 会员类型（0:非会员 1：会员）
     */
    public String getDisUserType() {
        return (String) get(6);
    }

    /**
     * Setter for <code>distribution.dis_profi_param.is_delete</code>.
     */
    public void setIsDelete(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>distribution.dis_profi_param.is_delete</code>.
     */
    public String getIsDelete() {
        return (String) get(7);
    }

    /**
     * Setter for <code>distribution.dis_profi_param.update_time</code>.
     */
    public void setUpdateTime(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>distribution.dis_profi_param.update_time</code>.
     */
    public String getUpdateTime() {
        return (String) get(8);
    }

    /**
     * Setter for <code>distribution.dis_profi_param.add_time</code>.
     */
    public void setAddTime(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>distribution.dis_profi_param.add_time</code>.
     */
    public String getAddTime() {
        return (String) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<String, String, String, String, Double, String, String, String, String, String> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<String, String, String, String, Double, String, String, String, String, String> valuesRow() {
        return (Row10) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return DisProfiParam.DIS_PROFI_PARAM.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return DisProfiParam.DIS_PROFI_PARAM.DIS_PLATFORM_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return DisProfiParam.DIS_PROFI_PARAM.DIS_PRO_MODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return DisProfiParam.DIS_PROFI_PARAM.DIS_PRO_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field5() {
        return DisProfiParam.DIS_PROFI_PARAM.DIS_PRO_VALUE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return DisProfiParam.DIS_PROFI_PARAM.DIS_PRO_LEVEL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return DisProfiParam.DIS_PROFI_PARAM.DIS_USER_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return DisProfiParam.DIS_PROFI_PARAM.IS_DELETE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return DisProfiParam.DIS_PROFI_PARAM.UPDATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return DisProfiParam.DIS_PROFI_PARAM.ADD_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getDisPlatformId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getDisProMode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getDisProType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component5() {
        return getDisProValue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getDisProLevel();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getDisUserType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getIsDelete();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component10() {
        return getAddTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getDisPlatformId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getDisProMode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getDisProType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value5() {
        return getDisProValue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getDisProLevel();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getDisUserType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getIsDelete();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getAddTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DisProfiParamRecord value1(String value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DisProfiParamRecord value2(String value) {
        setDisPlatformId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DisProfiParamRecord value3(String value) {
        setDisProMode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DisProfiParamRecord value4(String value) {
        setDisProType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DisProfiParamRecord value5(Double value) {
        setDisProValue(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DisProfiParamRecord value6(String value) {
        setDisProLevel(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DisProfiParamRecord value7(String value) {
        setDisUserType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DisProfiParamRecord value8(String value) {
        setIsDelete(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DisProfiParamRecord value9(String value) {
        setUpdateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DisProfiParamRecord value10(String value) {
        setAddTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DisProfiParamRecord values(String value1, String value2, String value3, String value4, Double value5, String value6, String value7, String value8, String value9, String value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DisProfiParamRecord
     */
    public DisProfiParamRecord() {
        super(DisProfiParam.DIS_PROFI_PARAM);
    }

    /**
     * Create a detached, initialised DisProfiParamRecord
     */
    public DisProfiParamRecord(String id, String disPlatformId, String disProMode, String disProType, Double disProValue, String disProLevel, String disUserType, String isDelete, String updateTime, String addTime) {
        super(DisProfiParam.DIS_PROFI_PARAM);

        set(0, id);
        set(1, disPlatformId);
        set(2, disProMode);
        set(3, disProType);
        set(4, disProValue);
        set(5, disProLevel);
        set(6, disUserType);
        set(7, isDelete);
        set(8, updateTime);
        set(9, addTime);
    }
}
