/*
 * This file is generated by jOOQ.
*/
package com.distribution.pojo.tables.records;


import com.distribution.pojo.tables.IntegralTutorial;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class IntegralTutorialRecord extends UpdatableRecordImpl<IntegralTutorialRecord> implements Record5<Integer, String, Integer, String, String> {

    private static final long serialVersionUID = -595579579;

    /**
     * Setter for <code>distribution_dev.integral_tutorial.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>distribution_dev.integral_tutorial.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>distribution_dev.integral_tutorial.type_id</code>. 产品类型ID
     */
    public void setTypeId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>distribution_dev.integral_tutorial.type_id</code>. 产品类型ID
     */
    public String getTypeId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>distribution_dev.integral_tutorial.step</code>. 步骤
     */
    public void setStep(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>distribution_dev.integral_tutorial.step</code>. 步骤
     */
    public Integer getStep() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>distribution_dev.integral_tutorial.text_describe</code>. 文字描述
     */
    public void setTextDescribe(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>distribution_dev.integral_tutorial.text_describe</code>. 文字描述
     */
    public String getTextDescribe() {
        return (String) get(3);
    }

    /**
     * Setter for <code>distribution_dev.integral_tutorial.img_describe</code>. 图片描述
     */
    public void setImgDescribe(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>distribution_dev.integral_tutorial.img_describe</code>. 图片描述
     */
    public String getImgDescribe() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, String, Integer, String, String> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, String, Integer, String, String> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return IntegralTutorial.INTEGRAL_TUTORIAL.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return IntegralTutorial.INTEGRAL_TUTORIAL.TYPE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return IntegralTutorial.INTEGRAL_TUTORIAL.STEP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return IntegralTutorial.INTEGRAL_TUTORIAL.TEXT_DESCRIBE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return IntegralTutorial.INTEGRAL_TUTORIAL.IMG_DESCRIBE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getTypeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getStep();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getTextDescribe();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getImgDescribe();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getTypeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getStep();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getTextDescribe();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getImgDescribe();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IntegralTutorialRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IntegralTutorialRecord value2(String value) {
        setTypeId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IntegralTutorialRecord value3(Integer value) {
        setStep(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IntegralTutorialRecord value4(String value) {
        setTextDescribe(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IntegralTutorialRecord value5(String value) {
        setImgDescribe(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IntegralTutorialRecord values(Integer value1, String value2, Integer value3, String value4, String value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached IntegralTutorialRecord
     */
    public IntegralTutorialRecord() {
        super(IntegralTutorial.INTEGRAL_TUTORIAL);
    }

    /**
     * Create a detached, initialised IntegralTutorialRecord
     */
    public IntegralTutorialRecord(Integer id, String typeId, Integer step, String textDescribe, String imgDescribe) {
        super(IntegralTutorial.INTEGRAL_TUTORIAL);

        set(0, id);
        set(1, typeId);
        set(2, step);
        set(3, textDescribe);
        set(4, imgDescribe);
    }
}
