/*
 * This file is generated by jOOQ.
*/
package com.distribution.pojo.tables.records;


import com.distribution.pojo.tables.LoanOrderInfo;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record12;
import org.jooq.Row12;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 贷款订单
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LoanOrderInfoRecord extends UpdatableRecordImpl<LoanOrderInfoRecord> implements Record12<String, String, String, String, String, String, String, Double, Integer, String, String, Double> {

    private static final long serialVersionUID = 463010056;

    /**
     * Setter for <code>distribution_dev.loan_order_info.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>distribution_dev.loan_order_info.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>distribution_dev.loan_order_info.order_id</code>. 订单编号
     */
    public void setOrderId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>distribution_dev.loan_order_info.order_id</code>. 订单编号
     */
    public String getOrderId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>distribution_dev.loan_order_info.order_mobile</code>.
     */
    public void setOrderMobile(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>distribution_dev.loan_order_info.order_mobile</code>.
     */
    public String getOrderMobile() {
        return (String) get(2);
    }

    /**
     * Setter for <code>distribution_dev.loan_order_info.order_idcardno</code>.
     */
    public void setOrderIdcardno(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>distribution_dev.loan_order_info.order_idcardno</code>.
     */
    public String getOrderIdcardno() {
        return (String) get(3);
    }

    /**
     * Setter for <code>distribution_dev.loan_order_info.order_status</code>. 订单状态 0失败 1成功 2申请中
     */
    public void setOrderStatus(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>distribution_dev.loan_order_info.order_status</code>. 订单状态 0失败 1成功 2申请中
     */
    public String getOrderStatus() {
        return (String) get(4);
    }

    /**
     * Setter for <code>distribution_dev.loan_order_info.member_id</code>.
     */
    public void setMemberId(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>distribution_dev.loan_order_info.member_id</code>.
     */
    public String getMemberId() {
        return (String) get(5);
    }

    /**
     * Setter for <code>distribution_dev.loan_order_info.loan_id</code>. 借款产品ID
     */
    public void setLoanId(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>distribution_dev.loan_order_info.loan_id</code>. 借款产品ID
     */
    public String getLoanId() {
        return (String) get(6);
    }

    /**
     * Setter for <code>distribution_dev.loan_order_info.loan_amount</code>. 本金
     */
    public void setLoanAmount(Double value) {
        set(7, value);
    }

    /**
     * Getter for <code>distribution_dev.loan_order_info.loan_amount</code>. 本金
     */
    public Double getLoanAmount() {
        return (Double) get(7);
    }

    /**
     * Setter for <code>distribution_dev.loan_order_info.is_delete</code>.
     */
    public void setIsDelete(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>distribution_dev.loan_order_info.is_delete</code>.
     */
    public Integer getIsDelete() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>distribution_dev.loan_order_info.add_time</code>.
     */
    public void setAddTime(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>distribution_dev.loan_order_info.add_time</code>.
     */
    public String getAddTime() {
        return (String) get(9);
    }

    /**
     * Setter for <code>distribution_dev.loan_order_info.update_time</code>.
     */
    public void setUpdateTime(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>distribution_dev.loan_order_info.update_time</code>.
     */
    public String getUpdateTime() {
        return (String) get(10);
    }

    /**
     * Setter for <code>distribution_dev.loan_order_info.loan_money</code>. 分润金额
     */
    public void setLoanMoney(Double value) {
        set(11, value);
    }

    /**
     * Getter for <code>distribution_dev.loan_order_info.loan_money</code>. 分润金额
     */
    public Double getLoanMoney() {
        return (Double) get(11);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record12 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row12<String, String, String, String, String, String, String, Double, Integer, String, String, Double> fieldsRow() {
        return (Row12) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row12<String, String, String, String, String, String, String, Double, Integer, String, String, Double> valuesRow() {
        return (Row12) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return LoanOrderInfo.LOAN_ORDER_INFO.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return LoanOrderInfo.LOAN_ORDER_INFO.ORDER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return LoanOrderInfo.LOAN_ORDER_INFO.ORDER_MOBILE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return LoanOrderInfo.LOAN_ORDER_INFO.ORDER_IDCARDNO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return LoanOrderInfo.LOAN_ORDER_INFO.ORDER_STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return LoanOrderInfo.LOAN_ORDER_INFO.MEMBER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return LoanOrderInfo.LOAN_ORDER_INFO.LOAN_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field8() {
        return LoanOrderInfo.LOAN_ORDER_INFO.LOAN_AMOUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field9() {
        return LoanOrderInfo.LOAN_ORDER_INFO.IS_DELETE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return LoanOrderInfo.LOAN_ORDER_INFO.ADD_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return LoanOrderInfo.LOAN_ORDER_INFO.UPDATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field12() {
        return LoanOrderInfo.LOAN_ORDER_INFO.LOAN_MONEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getOrderId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getOrderMobile();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getOrderIdcardno();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getOrderStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getMemberId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getLoanId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component8() {
        return getLoanAmount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component9() {
        return getIsDelete();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component10() {
        return getAddTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component11() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component12() {
        return getLoanMoney();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getOrderId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getOrderMobile();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getOrderIdcardno();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getOrderStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getMemberId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getLoanId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value8() {
        return getLoanAmount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value9() {
        return getIsDelete();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getAddTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value12() {
        return getLoanMoney();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LoanOrderInfoRecord value1(String value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LoanOrderInfoRecord value2(String value) {
        setOrderId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LoanOrderInfoRecord value3(String value) {
        setOrderMobile(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LoanOrderInfoRecord value4(String value) {
        setOrderIdcardno(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LoanOrderInfoRecord value5(String value) {
        setOrderStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LoanOrderInfoRecord value6(String value) {
        setMemberId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LoanOrderInfoRecord value7(String value) {
        setLoanId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LoanOrderInfoRecord value8(Double value) {
        setLoanAmount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LoanOrderInfoRecord value9(Integer value) {
        setIsDelete(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LoanOrderInfoRecord value10(String value) {
        setAddTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LoanOrderInfoRecord value11(String value) {
        setUpdateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LoanOrderInfoRecord value12(Double value) {
        setLoanMoney(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LoanOrderInfoRecord values(String value1, String value2, String value3, String value4, String value5, String value6, String value7, Double value8, Integer value9, String value10, String value11, Double value12) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LoanOrderInfoRecord
     */
    public LoanOrderInfoRecord() {
        super(LoanOrderInfo.LOAN_ORDER_INFO);
    }

    /**
     * Create a detached, initialised LoanOrderInfoRecord
     */
    public LoanOrderInfoRecord(String id, String orderId, String orderMobile, String orderIdcardno, String orderStatus, String memberId, String loanId, Double loanAmount, Integer isDelete, String addTime, String updateTime, Double loanMoney) {
        super(LoanOrderInfo.LOAN_ORDER_INFO);

        set(0, id);
        set(1, orderId);
        set(2, orderMobile);
        set(3, orderIdcardno);
        set(4, orderStatus);
        set(5, memberId);
        set(6, loanId);
        set(7, loanAmount);
        set(8, isDelete);
        set(9, addTime);
        set(10, updateTime);
        set(11, loanMoney);
    }
}
