/*
 * This file is generated by jOOQ.
*/
package com.distribution.pojo.tables.records;


import com.distribution.pojo.tables.MemberAccount;

import java.math.BigDecimal;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 会员账户表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MemberAccountRecord extends UpdatableRecordImpl<MemberAccountRecord> implements Record8<String, String, String, BigDecimal, String, String, String, String> {

    private static final long serialVersionUID = 1891197000;

    /**
     * Setter for <code>distribution.member_account.account_id</code>.
     */
    public void setAccountId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>distribution.member_account.account_id</code>.
     */
    public String getAccountId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>distribution.member_account.member_id</code>. 会员管理ID
     */
    public void setMemberId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>distribution.member_account.member_id</code>. 会员管理ID
     */
    public String getMemberId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>distribution.member_account.member_type</code>. 账户类型
     */
    public void setMemberType(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>distribution.member_account.member_type</code>. 账户类型
     */
    public String getMemberType() {
        return (String) get(2);
    }

    /**
     * Setter for <code>distribution.member_account.member_amount</code>.
     */
    public void setMemberAmount(BigDecimal value) {
        set(3, value);
    }

    /**
     * Getter for <code>distribution.member_account.member_amount</code>.
     */
    public BigDecimal getMemberAmount() {
        return (BigDecimal) get(3);
    }

    /**
     * Setter for <code>distribution.member_account.alipay_account</code>. 用户支付宝账号
     */
    public void setAlipayAccount(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>distribution.member_account.alipay_account</code>. 用户支付宝账号
     */
    public String getAlipayAccount() {
        return (String) get(4);
    }

    /**
     * Setter for <code>distribution.member_account.is_delete</code>.
     */
    public void setIsDelete(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>distribution.member_account.is_delete</code>.
     */
    public String getIsDelete() {
        return (String) get(5);
    }

    /**
     * Setter for <code>distribution.member_account.add_time</code>.
     */
    public void setAddTime(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>distribution.member_account.add_time</code>.
     */
    public String getAddTime() {
        return (String) get(6);
    }

    /**
     * Setter for <code>distribution.member_account.update_time</code>.
     */
    public void setUpdateTime(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>distribution.member_account.update_time</code>.
     */
    public String getUpdateTime() {
        return (String) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<String, String, String, BigDecimal, String, String, String, String> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<String, String, String, BigDecimal, String, String, String, String> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return MemberAccount.MEMBER_ACCOUNT.ACCOUNT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return MemberAccount.MEMBER_ACCOUNT.MEMBER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return MemberAccount.MEMBER_ACCOUNT.MEMBER_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field4() {
        return MemberAccount.MEMBER_ACCOUNT.MEMBER_AMOUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return MemberAccount.MEMBER_ACCOUNT.ALIPAY_ACCOUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return MemberAccount.MEMBER_ACCOUNT.IS_DELETE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return MemberAccount.MEMBER_ACCOUNT.ADD_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return MemberAccount.MEMBER_ACCOUNT.UPDATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getAccountId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getMemberId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getMemberType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component4() {
        return getMemberAmount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getAlipayAccount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getIsDelete();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getAddTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getAccountId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getMemberId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getMemberType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value4() {
        return getMemberAmount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getAlipayAccount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getIsDelete();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getAddTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MemberAccountRecord value1(String value) {
        setAccountId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MemberAccountRecord value2(String value) {
        setMemberId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MemberAccountRecord value3(String value) {
        setMemberType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MemberAccountRecord value4(BigDecimal value) {
        setMemberAmount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MemberAccountRecord value5(String value) {
        setAlipayAccount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MemberAccountRecord value6(String value) {
        setIsDelete(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MemberAccountRecord value7(String value) {
        setAddTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MemberAccountRecord value8(String value) {
        setUpdateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MemberAccountRecord values(String value1, String value2, String value3, BigDecimal value4, String value5, String value6, String value7, String value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MemberAccountRecord
     */
    public MemberAccountRecord() {
        super(MemberAccount.MEMBER_ACCOUNT);
    }

    /**
     * Create a detached, initialised MemberAccountRecord
     */
    public MemberAccountRecord(String accountId, String memberId, String memberType, BigDecimal memberAmount, String alipayAccount, String isDelete, String addTime, String updateTime) {
        super(MemberAccount.MEMBER_ACCOUNT);

        set(0, accountId);
        set(1, memberId);
        set(2, memberType);
        set(3, memberAmount);
        set(4, alipayAccount);
        set(5, isDelete);
        set(6, addTime);
        set(7, updateTime);
    }
}
