/*
 * This file is generated by jOOQ.
*/
package com.distribution.pojo.tables.records;


import com.distribution.pojo.tables.MemberAccountHistory;

import java.math.BigDecimal;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 用户金额变化表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MemberAccountHistoryRecord extends UpdatableRecordImpl<MemberAccountHistoryRecord> implements Record8<String, Integer, String, BigDecimal, String, String, String, String> {

    private static final long serialVersionUID = -655817509;

    /**
     * Setter for <code>distribution_dev.member_account_history.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>distribution_dev.member_account_history.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>distribution_dev.member_account_history.his_type</code>. 收入类型，0:支出,1:收入
     */
    public void setHisType(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>distribution_dev.member_account_history.his_type</code>. 收入类型，0:支出,1:收入
     */
    public Integer getHisType() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>distribution_dev.member_account_history.account_id</code>. 关联的订单ID
     */
    public void setAccountId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>distribution_dev.member_account_history.account_id</code>. 关联的订单ID
     */
    public String getAccountId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>distribution_dev.member_account_history.his_amount</code>.
     */
    public void setHisAmount(BigDecimal value) {
        set(3, value);
    }

    /**
     * Getter for <code>distribution_dev.member_account_history.his_amount</code>.
     */
    public BigDecimal getHisAmount() {
        return (BigDecimal) get(3);
    }

    /**
     * Setter for <code>distribution_dev.member_account_history.his_note</code>.
     */
    public void setHisNote(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>distribution_dev.member_account_history.his_note</code>.
     */
    public String getHisNote() {
        return (String) get(4);
    }

    /**
     * Setter for <code>distribution_dev.member_account_history.is_delete</code>.
     */
    public void setIsDelete(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>distribution_dev.member_account_history.is_delete</code>.
     */
    public String getIsDelete() {
        return (String) get(5);
    }

    /**
     * Setter for <code>distribution_dev.member_account_history.add_time</code>.
     */
    public void setAddTime(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>distribution_dev.member_account_history.add_time</code>.
     */
    public String getAddTime() {
        return (String) get(6);
    }

    /**
     * Setter for <code>distribution_dev.member_account_history.update_time</code>.
     */
    public void setUpdateTime(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>distribution_dev.member_account_history.update_time</code>.
     */
    public String getUpdateTime() {
        return (String) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<String, Integer, String, BigDecimal, String, String, String, String> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<String, Integer, String, BigDecimal, String, String, String, String> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return MemberAccountHistory.MEMBER_ACCOUNT_HISTORY.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return MemberAccountHistory.MEMBER_ACCOUNT_HISTORY.HIS_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return MemberAccountHistory.MEMBER_ACCOUNT_HISTORY.ACCOUNT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field4() {
        return MemberAccountHistory.MEMBER_ACCOUNT_HISTORY.HIS_AMOUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return MemberAccountHistory.MEMBER_ACCOUNT_HISTORY.HIS_NOTE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return MemberAccountHistory.MEMBER_ACCOUNT_HISTORY.IS_DELETE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return MemberAccountHistory.MEMBER_ACCOUNT_HISTORY.ADD_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return MemberAccountHistory.MEMBER_ACCOUNT_HISTORY.UPDATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getHisType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getAccountId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component4() {
        return getHisAmount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getHisNote();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getIsDelete();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getAddTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getHisType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getAccountId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value4() {
        return getHisAmount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getHisNote();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getIsDelete();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getAddTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MemberAccountHistoryRecord value1(String value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MemberAccountHistoryRecord value2(Integer value) {
        setHisType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MemberAccountHistoryRecord value3(String value) {
        setAccountId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MemberAccountHistoryRecord value4(BigDecimal value) {
        setHisAmount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MemberAccountHistoryRecord value5(String value) {
        setHisNote(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MemberAccountHistoryRecord value6(String value) {
        setIsDelete(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MemberAccountHistoryRecord value7(String value) {
        setAddTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MemberAccountHistoryRecord value8(String value) {
        setUpdateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MemberAccountHistoryRecord values(String value1, Integer value2, String value3, BigDecimal value4, String value5, String value6, String value7, String value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MemberAccountHistoryRecord
     */
    public MemberAccountHistoryRecord() {
        super(MemberAccountHistory.MEMBER_ACCOUNT_HISTORY);
    }

    /**
     * Create a detached, initialised MemberAccountHistoryRecord
     */
    public MemberAccountHistoryRecord(String id, Integer hisType, String accountId, BigDecimal hisAmount, String hisNote, String isDelete, String addTime, String updateTime) {
        super(MemberAccountHistory.MEMBER_ACCOUNT_HISTORY);

        set(0, id);
        set(1, hisType);
        set(2, accountId);
        set(3, hisAmount);
        set(4, hisNote);
        set(5, isDelete);
        set(6, addTime);
        set(7, updateTime);
    }
}
