/*
 * This file is generated by jOOQ.
*/
package com.distribution.pojo.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * 轮播图
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AdPicture implements Serializable {

    private static final long serialVersionUID = 1799600086;

    private Integer id;
    private String  imgUrl;
    private Integer articleId;
    private Integer orderNum;
    private String  addTime;
    private String  isDelete;

    public AdPicture() {}

    public AdPicture(AdPicture value) {
        this.id = value.id;
        this.imgUrl = value.imgUrl;
        this.articleId = value.articleId;
        this.orderNum = value.orderNum;
        this.addTime = value.addTime;
        this.isDelete = value.isDelete;
    }

    public AdPicture(
        Integer id,
        String  imgUrl,
        Integer articleId,
        Integer orderNum,
        String  addTime,
        String  isDelete
    ) {
        this.id = id;
        this.imgUrl = imgUrl;
        this.articleId = articleId;
        this.orderNum = orderNum;
        this.addTime = addTime;
        this.isDelete = isDelete;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getImgUrl() {
        return this.imgUrl;
    }

    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl;
    }

    public Integer getArticleId() {
        return this.articleId;
    }

    public void setArticleId(Integer articleId) {
        this.articleId = articleId;
    }

    public Integer getOrderNum() {
        return this.orderNum;
    }

    public void setOrderNum(Integer orderNum) {
        this.orderNum = orderNum;
    }

    public String getAddTime() {
        return this.addTime;
    }

    public void setAddTime(String addTime) {
        this.addTime = addTime;
    }

    public String getIsDelete() {
        return this.isDelete;
    }

    public void setIsDelete(String isDelete) {
        this.isDelete = isDelete;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("AdPicture (");

        sb.append(id);
        sb.append(", ").append(imgUrl);
        sb.append(", ").append(articleId);
        sb.append(", ").append(orderNum);
        sb.append(", ").append(addTime);
        sb.append(", ").append(isDelete);

        sb.append(")");
        return sb.toString();
    }
}
