/*
 * This file is generated by jOOQ.
*/
package com.distribution.pojo.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * 办卡订单信息表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CardOrderInfo implements Serializable {

    private static final long serialVersionUID = 2026573190;

    private String  id;
    private String  orderName;
    private String  orderId;
    private String  orderMobile;
    private String  orderIdcardno;
    private String  orderEmail;
    private Integer orderStatus;
    private String  memberId;
    private String  cardId;
    private String  isDelete;
    private String  addTime;
    private String  updateTime;
    private Integer orderBankStatus;

    public CardOrderInfo() {}

    public CardOrderInfo(CardOrderInfo value) {
        this.id = value.id;
        this.orderName = value.orderName;
        this.orderId = value.orderId;
        this.orderMobile = value.orderMobile;
        this.orderIdcardno = value.orderIdcardno;
        this.orderEmail = value.orderEmail;
        this.orderStatus = value.orderStatus;
        this.memberId = value.memberId;
        this.cardId = value.cardId;
        this.isDelete = value.isDelete;
        this.addTime = value.addTime;
        this.updateTime = value.updateTime;
        this.orderBankStatus = value.orderBankStatus;
    }

    public CardOrderInfo(
        String  id,
        String  orderName,
        String  orderId,
        String  orderMobile,
        String  orderIdcardno,
        String  orderEmail,
        Integer orderStatus,
        String  memberId,
        String  cardId,
        String  isDelete,
        String  addTime,
        String  updateTime,
        Integer orderBankStatus
    ) {
        this.id = id;
        this.orderName = orderName;
        this.orderId = orderId;
        this.orderMobile = orderMobile;
        this.orderIdcardno = orderIdcardno;
        this.orderEmail = orderEmail;
        this.orderStatus = orderStatus;
        this.memberId = memberId;
        this.cardId = cardId;
        this.isDelete = isDelete;
        this.addTime = addTime;
        this.updateTime = updateTime;
        this.orderBankStatus = orderBankStatus;
    }

    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getOrderName() {
        return this.orderName;
    }

    public void setOrderName(String orderName) {
        this.orderName = orderName;
    }

    public String getOrderId() {
        return this.orderId;
    }

    public void setOrderId(String orderId) {
        this.orderId = orderId;
    }

    public String getOrderMobile() {
        return this.orderMobile;
    }

    public void setOrderMobile(String orderMobile) {
        this.orderMobile = orderMobile;
    }

    public String getOrderIdcardno() {
        return this.orderIdcardno;
    }

    public void setOrderIdcardno(String orderIdcardno) {
        this.orderIdcardno = orderIdcardno;
    }

    public String getOrderEmail() {
        return this.orderEmail;
    }

    public void setOrderEmail(String orderEmail) {
        this.orderEmail = orderEmail;
    }

    public Integer getOrderStatus() {
        return this.orderStatus;
    }

    public void setOrderStatus(Integer orderStatus) {
        this.orderStatus = orderStatus;
    }

    public String getMemberId() {
        return this.memberId;
    }

    public void setMemberId(String memberId) {
        this.memberId = memberId;
    }

    public String getCardId() {
        return this.cardId;
    }

    public void setCardId(String cardId) {
        this.cardId = cardId;
    }

    public String getIsDelete() {
        return this.isDelete;
    }

    public void setIsDelete(String isDelete) {
        this.isDelete = isDelete;
    }

    public String getAddTime() {
        return this.addTime;
    }

    public void setAddTime(String addTime) {
        this.addTime = addTime;
    }

    public String getUpdateTime() {
        return this.updateTime;
    }

    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime;
    }

    public Integer getOrderBankStatus() {
        return this.orderBankStatus;
    }

    public void setOrderBankStatus(Integer orderBankStatus) {
        this.orderBankStatus = orderBankStatus;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("CardOrderInfo (");

        sb.append(id);
        sb.append(", ").append(orderName);
        sb.append(", ").append(orderId);
        sb.append(", ").append(orderMobile);
        sb.append(", ").append(orderIdcardno);
        sb.append(", ").append(orderEmail);
        sb.append(", ").append(orderStatus);
        sb.append(", ").append(memberId);
        sb.append(", ").append(cardId);
        sb.append(", ").append(isDelete);
        sb.append(", ").append(addTime);
        sb.append(", ").append(updateTime);
        sb.append(", ").append(orderBankStatus);

        sb.append(")");
        return sb.toString();
    }
}
