/*
 * This file is generated by jOOQ.
*/
package com.distribution.pojo.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * 字典表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DisDictionary implements Serializable {

    private static final long serialVersionUID = -1185403103;

    private Integer id;
    private String  disCode;
    private String  disType;
    private String  disValue;
    private Integer disSort;
    private String  disSysId;
    private String  isDelete;
    private String  addTime;
    private String  updateTime;

    public DisDictionary() {}

    public DisDictionary(DisDictionary value) {
        this.id = value.id;
        this.disCode = value.disCode;
        this.disType = value.disType;
        this.disValue = value.disValue;
        this.disSort = value.disSort;
        this.disSysId = value.disSysId;
        this.isDelete = value.isDelete;
        this.addTime = value.addTime;
        this.updateTime = value.updateTime;
    }

    public DisDictionary(
        Integer id,
        String  disCode,
        String  disType,
        String  disValue,
        Integer disSort,
        String  disSysId,
        String  isDelete,
        String  addTime,
        String  updateTime
    ) {
        this.id = id;
        this.disCode = disCode;
        this.disType = disType;
        this.disValue = disValue;
        this.disSort = disSort;
        this.disSysId = disSysId;
        this.isDelete = isDelete;
        this.addTime = addTime;
        this.updateTime = updateTime;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getDisCode() {
        return this.disCode;
    }

    public void setDisCode(String disCode) {
        this.disCode = disCode;
    }

    public String getDisType() {
        return this.disType;
    }

    public void setDisType(String disType) {
        this.disType = disType;
    }

    public String getDisValue() {
        return this.disValue;
    }

    public void setDisValue(String disValue) {
        this.disValue = disValue;
    }

    public Integer getDisSort() {
        return this.disSort;
    }

    public void setDisSort(Integer disSort) {
        this.disSort = disSort;
    }

    public String getDisSysId() {
        return this.disSysId;
    }

    public void setDisSysId(String disSysId) {
        this.disSysId = disSysId;
    }

    public String getIsDelete() {
        return this.isDelete;
    }

    public void setIsDelete(String isDelete) {
        this.isDelete = isDelete;
    }

    public String getAddTime() {
        return this.addTime;
    }

    public void setAddTime(String addTime) {
        this.addTime = addTime;
    }

    public String getUpdateTime() {
        return this.updateTime;
    }

    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("DisDictionary (");

        sb.append(id);
        sb.append(", ").append(disCode);
        sb.append(", ").append(disType);
        sb.append(", ").append(disValue);
        sb.append(", ").append(disSort);
        sb.append(", ").append(disSysId);
        sb.append(", ").append(isDelete);
        sb.append(", ").append(addTime);
        sb.append(", ").append(updateTime);

        sb.append(")");
        return sb.toString();
    }
}
