/*
 * This file is generated by jOOQ.
*/
package com.distribution.pojo.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * 意见反馈表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Feedback implements Serializable {

    private static final long serialVersionUID = 194630583;

    private Long    id;
    private String  memberId;
    private String  title;
    private String  content;
    private String  addTime;
    private Integer isDelete;

    public Feedback() {}

    public Feedback(Feedback value) {
        this.id = value.id;
        this.memberId = value.memberId;
        this.title = value.title;
        this.content = value.content;
        this.addTime = value.addTime;
        this.isDelete = value.isDelete;
    }

    public Feedback(
        Long    id,
        String  memberId,
        String  title,
        String  content,
        String  addTime,
        Integer isDelete
    ) {
        this.id = id;
        this.memberId = memberId;
        this.title = title;
        this.content = content;
        this.addTime = addTime;
        this.isDelete = isDelete;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getMemberId() {
        return this.memberId;
    }

    public void setMemberId(String memberId) {
        this.memberId = memberId;
    }

    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getContent() {
        return this.content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public String getAddTime() {
        return this.addTime;
    }

    public void setAddTime(String addTime) {
        this.addTime = addTime;
    }

    public Integer getIsDelete() {
        return this.isDelete;
    }

    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Feedback (");

        sb.append(id);
        sb.append(", ").append(memberId);
        sb.append(", ").append(title);
        sb.append(", ").append(content);
        sb.append(", ").append(addTime);
        sb.append(", ").append(isDelete);

        sb.append(")");
        return sb.toString();
    }
}
