/*
 * This file is generated by jOOQ.
*/
package com.distribution.pojo.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PosOrderInfo implements Serializable {

    private static final long serialVersionUID = -14627485;

    private String  id;
    private String  orderName;
    private String  orderId;
    private String  memberId;
    private String  personName;
    private String  personMobile;
    private String  storeName;
    private String  provinceName;
    private String  cityName;
    private Integer ifChain;
    private String  addTime;
    private String  updateTime;

    public PosOrderInfo() {}

    public PosOrderInfo(PosOrderInfo value) {
        this.id = value.id;
        this.orderName = value.orderName;
        this.orderId = value.orderId;
        this.memberId = value.memberId;
        this.personName = value.personName;
        this.personMobile = value.personMobile;
        this.storeName = value.storeName;
        this.provinceName = value.provinceName;
        this.cityName = value.cityName;
        this.ifChain = value.ifChain;
        this.addTime = value.addTime;
        this.updateTime = value.updateTime;
    }

    public PosOrderInfo(
        String  id,
        String  orderName,
        String  orderId,
        String  memberId,
        String  personName,
        String  personMobile,
        String  storeName,
        String  provinceName,
        String  cityName,
        Integer ifChain,
        String  addTime,
        String  updateTime
    ) {
        this.id = id;
        this.orderName = orderName;
        this.orderId = orderId;
        this.memberId = memberId;
        this.personName = personName;
        this.personMobile = personMobile;
        this.storeName = storeName;
        this.provinceName = provinceName;
        this.cityName = cityName;
        this.ifChain = ifChain;
        this.addTime = addTime;
        this.updateTime = updateTime;
    }

    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getOrderName() {
        return this.orderName;
    }

    public void setOrderName(String orderName) {
        this.orderName = orderName;
    }

    public String getOrderId() {
        return this.orderId;
    }

    public void setOrderId(String orderId) {
        this.orderId = orderId;
    }

    public String getMemberId() {
        return this.memberId;
    }

    public void setMemberId(String memberId) {
        this.memberId = memberId;
    }

    public String getPersonName() {
        return this.personName;
    }

    public void setPersonName(String personName) {
        this.personName = personName;
    }

    public String getPersonMobile() {
        return this.personMobile;
    }

    public void setPersonMobile(String personMobile) {
        this.personMobile = personMobile;
    }

    public String getStoreName() {
        return this.storeName;
    }

    public void setStoreName(String storeName) {
        this.storeName = storeName;
    }

    public String getProvinceName() {
        return this.provinceName;
    }

    public void setProvinceName(String provinceName) {
        this.provinceName = provinceName;
    }

    public String getCityName() {
        return this.cityName;
    }

    public void setCityName(String cityName) {
        this.cityName = cityName;
    }

    public Integer getIfChain() {
        return this.ifChain;
    }

    public void setIfChain(Integer ifChain) {
        this.ifChain = ifChain;
    }

    public String getAddTime() {
        return this.addTime;
    }

    public void setAddTime(String addTime) {
        this.addTime = addTime;
    }

    public String getUpdateTime() {
        return this.updateTime;
    }

    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("PosOrderInfo (");

        sb.append(id);
        sb.append(", ").append(orderName);
        sb.append(", ").append(orderId);
        sb.append(", ").append(memberId);
        sb.append(", ").append(personName);
        sb.append(", ").append(personMobile);
        sb.append(", ").append(storeName);
        sb.append(", ").append(provinceName);
        sb.append(", ").append(cityName);
        sb.append(", ").append(ifChain);
        sb.append(", ").append(addTime);
        sb.append(", ").append(updateTime);

        sb.append(")");
        return sb.toString();
    }
}
