/*
 * This file is generated by jOOQ.
*/
package com.distribution.pojo.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * ????
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysOss implements Serializable {

    private static final long serialVersionUID = -1632773978;

    private Long      id;
    private String    url;
    private Timestamp createDate;

    public SysOss() {}

    public SysOss(SysOss value) {
        this.id = value.id;
        this.url = value.url;
        this.createDate = value.createDate;
    }

    public SysOss(
        Long      id,
        String    url,
        Timestamp createDate
    ) {
        this.id = id;
        this.url = url;
        this.createDate = createDate;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUrl() {
        return this.url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public Timestamp getCreateDate() {
        return this.createDate;
    }

    public void setCreateDate(Timestamp createDate) {
        this.createDate = createDate;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("SysOss (");

        sb.append(id);
        sb.append(", ").append(url);
        sb.append(", ").append(createDate);

        sb.append(")");
        return sb.toString();
    }
}
