/*
 * This file is generated by jOOQ.
*/
package com.distribution.pojo.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;

import javax.annotation.Generated;


/**
 * 提现信息表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WithdrawalInfo implements Serializable {

    private static final long serialVersionUID = 1076448042;

    private String     id;
    private String     withdrawNum;
    private String     withdrawType;
    private String     withdrawName;
    private String     withdrawMobile;
    private String     withdrawCard;
    private BigDecimal withdrawAmount;
    private BigDecimal withdrawPoundage;
    private BigDecimal realAmount;
    private String     alipayAccount;
    private String     isDelete;
    private String     addTime;
    private String     updateTime;

    public WithdrawalInfo() {}

    public WithdrawalInfo(WithdrawalInfo value) {
        this.id = value.id;
        this.withdrawNum = value.withdrawNum;
        this.withdrawType = value.withdrawType;
        this.withdrawName = value.withdrawName;
        this.withdrawMobile = value.withdrawMobile;
        this.withdrawCard = value.withdrawCard;
        this.withdrawAmount = value.withdrawAmount;
        this.withdrawPoundage = value.withdrawPoundage;
        this.realAmount = value.realAmount;
        this.alipayAccount = value.alipayAccount;
        this.isDelete = value.isDelete;
        this.addTime = value.addTime;
        this.updateTime = value.updateTime;
    }

    public WithdrawalInfo(
        String     id,
        String     withdrawNum,
        String     withdrawType,
        String     withdrawName,
        String     withdrawMobile,
        String     withdrawCard,
        BigDecimal withdrawAmount,
        BigDecimal withdrawPoundage,
        BigDecimal realAmount,
        String     alipayAccount,
        String     isDelete,
        String     addTime,
        String     updateTime
    ) {
        this.id = id;
        this.withdrawNum = withdrawNum;
        this.withdrawType = withdrawType;
        this.withdrawName = withdrawName;
        this.withdrawMobile = withdrawMobile;
        this.withdrawCard = withdrawCard;
        this.withdrawAmount = withdrawAmount;
        this.withdrawPoundage = withdrawPoundage;
        this.realAmount = realAmount;
        this.alipayAccount = alipayAccount;
        this.isDelete = isDelete;
        this.addTime = addTime;
        this.updateTime = updateTime;
    }

    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getWithdrawNum() {
        return this.withdrawNum;
    }

    public void setWithdrawNum(String withdrawNum) {
        this.withdrawNum = withdrawNum;
    }

    public String getWithdrawType() {
        return this.withdrawType;
    }

    public void setWithdrawType(String withdrawType) {
        this.withdrawType = withdrawType;
    }

    public String getWithdrawName() {
        return this.withdrawName;
    }

    public void setWithdrawName(String withdrawName) {
        this.withdrawName = withdrawName;
    }

    public String getWithdrawMobile() {
        return this.withdrawMobile;
    }

    public void setWithdrawMobile(String withdrawMobile) {
        this.withdrawMobile = withdrawMobile;
    }

    public String getWithdrawCard() {
        return this.withdrawCard;
    }

    public void setWithdrawCard(String withdrawCard) {
        this.withdrawCard = withdrawCard;
    }

    public BigDecimal getWithdrawAmount() {
        return this.withdrawAmount;
    }

    public void setWithdrawAmount(BigDecimal withdrawAmount) {
        this.withdrawAmount = withdrawAmount;
    }

    public BigDecimal getWithdrawPoundage() {
        return this.withdrawPoundage;
    }

    public void setWithdrawPoundage(BigDecimal withdrawPoundage) {
        this.withdrawPoundage = withdrawPoundage;
    }

    public BigDecimal getRealAmount() {
        return this.realAmount;
    }

    public void setRealAmount(BigDecimal realAmount) {
        this.realAmount = realAmount;
    }

    public String getAlipayAccount() {
        return this.alipayAccount;
    }

    public void setAlipayAccount(String alipayAccount) {
        this.alipayAccount = alipayAccount;
    }

    public String getIsDelete() {
        return this.isDelete;
    }

    public void setIsDelete(String isDelete) {
        this.isDelete = isDelete;
    }

    public String getAddTime() {
        return this.addTime;
    }

    public void setAddTime(String addTime) {
        this.addTime = addTime;
    }

    public String getUpdateTime() {
        return this.updateTime;
    }

    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("WithdrawalInfo (");

        sb.append(id);
        sb.append(", ").append(withdrawNum);
        sb.append(", ").append(withdrawType);
        sb.append(", ").append(withdrawName);
        sb.append(", ").append(withdrawMobile);
        sb.append(", ").append(withdrawCard);
        sb.append(", ").append(withdrawAmount);
        sb.append(", ").append(withdrawPoundage);
        sb.append(", ").append(realAmount);
        sb.append(", ").append(alipayAccount);
        sb.append(", ").append(isDelete);
        sb.append(", ").append(addTime);
        sb.append(", ").append(updateTime);

        sb.append(")");
        return sb.toString();
    }
}
