package com.distribution.modules.dis.entity

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table dis_fans
 *
 * @mbg.generated do_not_delete_during_merge
 */
data class DisFans(
        var id: String = "",
        var disMemberInfo: DisMemberInfoEntity? = DisMemberInfoEntity(),
        var wechatId: String = "",
        var wechatImg: String = "",
        var wechatNickname: String = "",
        var workerId: Long = 0
)