package com.distribution.modules.dis.entity;

import lombok.Data;
import org.springframework.format.annotation.DateTimeFormat;

import java.time.LocalDateTime;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table order_history
 *
 * @mbg.generated do_not_delete_during_merge
 */
@Data
public class OrderHistory {
    /**
     * 订单号
     */
    private String orderId;

    /**
     * 交易手机号
     */
    private String mobile;

    /**
     * 交易账号 支付宝账号
     */
    private String account;

    /**
     * 订单金额
     */
    private Double amount;

    /**
     * 订单状态 0:失败,1:成功,2:未支付
     */
    private Integer orderStatus;

    /** */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:SS")
    private LocalDateTime addTime;

    /**
     * 订单完成时间,支付成功时间
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:SS")
    private LocalDateTime finishTime;

}