/*
 * This file is generated by jOOQ.
*/
package com.distribution.pojo;


import com.distribution.pojo.tables.AdPicture;
import com.distribution.pojo.tables.ArticleInfo;
import com.distribution.pojo.tables.CardInfo;
import com.distribution.pojo.tables.CardOrderInfo;
import com.distribution.pojo.tables.DisDictionary;
import com.distribution.pojo.tables.DisFans;
import com.distribution.pojo.tables.DisMemberInfo;
import com.distribution.pojo.tables.DisProfiParam;
import com.distribution.pojo.tables.DisProfitRecord;
import com.distribution.pojo.tables.District;
import com.distribution.pojo.tables.Feedback;
import com.distribution.pojo.tables.IntegralOrder;
import com.distribution.pojo.tables.IntegralTutorial;
import com.distribution.pojo.tables.LoanInfo;
import com.distribution.pojo.tables.LoanOrderInfo;
import com.distribution.pojo.tables.MemberAccount;
import com.distribution.pojo.tables.MemberAccountHistory;
import com.distribution.pojo.tables.MemeberInfo;
import com.distribution.pojo.tables.MobileMessage;
import com.distribution.pojo.tables.PosApply;
import com.distribution.pojo.tables.PosOrderInfo;
import com.distribution.pojo.tables.ProductDetail;
import com.distribution.pojo.tables.ProductDetailParams;
import com.distribution.pojo.tables.ProductType;
import com.distribution.pojo.tables.ProductTypeParams;
import com.distribution.pojo.tables.ScheduleJob;
import com.distribution.pojo.tables.ScheduleJobLog;
import com.distribution.pojo.tables.SysConfig;
import com.distribution.pojo.tables.SysLog;
import com.distribution.pojo.tables.SysMenu;
import com.distribution.pojo.tables.SysOss;
import com.distribution.pojo.tables.SysRole;
import com.distribution.pojo.tables.SysRoleMenu;
import com.distribution.pojo.tables.SysUser;
import com.distribution.pojo.tables.SysUserRole;
import com.distribution.pojo.tables.SysUserToken;
import com.distribution.pojo.tables.TbToken;
import com.distribution.pojo.tables.TbUser;
import com.distribution.pojo.tables.WithdrawalInfo;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>distribution_dev</code> 
 * schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index AD_PICTURE_AD_PICTURE_ARTICLE_ID_INDEX = Indexes0.AD_PICTURE_AD_PICTURE_ARTICLE_ID_INDEX;
    public static final Index AD_PICTURE_AD_PICTURE_ID_INDEX = Indexes0.AD_PICTURE_AD_PICTURE_ID_INDEX;
    public static final Index AD_PICTURE_PRIMARY = Indexes0.AD_PICTURE_PRIMARY;
    public static final Index ARTICLE_INFO_ARTICLE_INFO_ID_INDEX = Indexes0.ARTICLE_INFO_ARTICLE_INFO_ID_INDEX;
    public static final Index ARTICLE_INFO_PRIMARY = Indexes0.ARTICLE_INFO_PRIMARY;
    public static final Index CARD_INFO_CARD_INFO_BANK_NUM_INDEX = Indexes0.CARD_INFO_CARD_INFO_BANK_NUM_INDEX;
    public static final Index CARD_INFO_CARD_INFO_CARD_NUM_INDEX = Indexes0.CARD_INFO_CARD_INFO_CARD_NUM_INDEX;
    public static final Index CARD_INFO_CARD_INFO_ID_UINDEX = Indexes0.CARD_INFO_CARD_INFO_ID_UINDEX;
    public static final Index CARD_INFO_PRIMARY = Indexes0.CARD_INFO_PRIMARY;
    public static final Index CARD_ORDER_INFO_CARD_ORDER_INFO_ID_UINDEX = Indexes0.CARD_ORDER_INFO_CARD_ORDER_INFO_ID_UINDEX;
    public static final Index CARD_ORDER_INFO_CARD_ORDER_INFO__INDEX_1 = Indexes0.CARD_ORDER_INFO_CARD_ORDER_INFO__INDEX_1;
    public static final Index CARD_ORDER_INFO_CARD_ORDER_INFO__INDEX_2 = Indexes0.CARD_ORDER_INFO_CARD_ORDER_INFO__INDEX_2;
    public static final Index CARD_ORDER_INFO_CARD_ORDER_INFO__INDEX_3 = Indexes0.CARD_ORDER_INFO_CARD_ORDER_INFO__INDEX_3;
    public static final Index CARD_ORDER_INFO_PRIMARY = Indexes0.CARD_ORDER_INFO_PRIMARY;
    public static final Index DISTRICT_DISTRICT_ID_INDEX = Indexes0.DISTRICT_DISTRICT_ID_INDEX;
    public static final Index DISTRICT_DISTRICT_PARENT_ID_INDEX = Indexes0.DISTRICT_DISTRICT_PARENT_ID_INDEX;
    public static final Index DIS_DICTIONARY_PRIMARY = Indexes0.DIS_DICTIONARY_PRIMARY;
    public static final Index DIS_FANS_DIS_FANS_ID_UINDEX = Indexes0.DIS_FANS_DIS_FANS_ID_UINDEX;
    public static final Index DIS_FANS_DIS_FANS__INDEX_1 = Indexes0.DIS_FANS_DIS_FANS__INDEX_1;
    public static final Index DIS_FANS_DIS_FANS__INDEX_OPENID = Indexes0.DIS_FANS_DIS_FANS__INDEX_OPENID;
    public static final Index DIS_FANS_PRIMARY = Indexes0.DIS_FANS_PRIMARY;
    public static final Index DIS_MEMBER_INFO_DIS_MEMBER_INFO_ID_UINDEX = Indexes0.DIS_MEMBER_INFO_DIS_MEMBER_INFO_ID_UINDEX;
    public static final Index DIS_MEMBER_INFO_DIS_MEMBER_INFO__INDEX_1 = Indexes0.DIS_MEMBER_INFO_DIS_MEMBER_INFO__INDEX_1;
    public static final Index DIS_MEMBER_INFO_DIS_MEMBER_INFO__INDEX_2 = Indexes0.DIS_MEMBER_INFO_DIS_MEMBER_INFO__INDEX_2;
    public static final Index DIS_MEMBER_INFO_DIS_MEMBER_INFO__INDEX_3 = Indexes0.DIS_MEMBER_INFO_DIS_MEMBER_INFO__INDEX_3;
    public static final Index DIS_MEMBER_INFO_DIS_MEMBER_INFO__INDEX_4 = Indexes0.DIS_MEMBER_INFO_DIS_MEMBER_INFO__INDEX_4;
    public static final Index DIS_MEMBER_INFO_DIS_MEMBER_INFO__INDEX_5 = Indexes0.DIS_MEMBER_INFO_DIS_MEMBER_INFO__INDEX_5;
    public static final Index DIS_MEMBER_INFO_PRIMARY = Indexes0.DIS_MEMBER_INFO_PRIMARY;
    public static final Index DIS_PROFIT_RECORD_DIS_PROFIT_RECORD_ID_UINDEX = Indexes0.DIS_PROFIT_RECORD_DIS_PROFIT_RECORD_ID_UINDEX;
    public static final Index DIS_PROFIT_RECORD_PRIMARY = Indexes0.DIS_PROFIT_RECORD_PRIMARY;
    public static final Index DIS_PROFI_PARAM_DIS_PROFI_PARAM_ID_UINDEX = Indexes0.DIS_PROFI_PARAM_DIS_PROFI_PARAM_ID_UINDEX;
    public static final Index DIS_PROFI_PARAM_PRIMARY = Indexes0.DIS_PROFI_PARAM_PRIMARY;
    public static final Index FEEDBACK_FEEDBACK_ID_INDEX = Indexes0.FEEDBACK_FEEDBACK_ID_INDEX;
    public static final Index FEEDBACK_FEEDBACK_MEMBER_ID_INDEX = Indexes0.FEEDBACK_FEEDBACK_MEMBER_ID_INDEX;
    public static final Index FEEDBACK_PRIMARY = Indexes0.FEEDBACK_PRIMARY;
    public static final Index INTEGRAL_ORDER_INTEGRAL_ORDER_DETAIL_ID_INDEX = Indexes0.INTEGRAL_ORDER_INTEGRAL_ORDER_DETAIL_ID_INDEX;
    public static final Index INTEGRAL_ORDER_INTEGRAL_ORDER_ID_UINDEX = Indexes0.INTEGRAL_ORDER_INTEGRAL_ORDER_ID_UINDEX;
    public static final Index INTEGRAL_ORDER_INTEGRAL_ORDER_MOBILE_INDEX = Indexes0.INTEGRAL_ORDER_INTEGRAL_ORDER_MOBILE_INDEX;
    public static final Index INTEGRAL_ORDER_PRIMARY = Indexes0.INTEGRAL_ORDER_PRIMARY;
    public static final Index INTEGRAL_TUTORIAL_PRIMARY = Indexes0.INTEGRAL_TUTORIAL_PRIMARY;
    public static final Index LOAN_INFO_LOAN_INFO_ID_UINDEX = Indexes0.LOAN_INFO_LOAN_INFO_ID_UINDEX;
    public static final Index LOAN_INFO_PRIMARY = Indexes0.LOAN_INFO_PRIMARY;
    public static final Index LOAN_ORDER_INFO_LOAN_ORDER_INFO_ID_UINDEX = Indexes0.LOAN_ORDER_INFO_LOAN_ORDER_INFO_ID_UINDEX;
    public static final Index LOAN_ORDER_INFO_LOAN_ORDER_INFO_LOAN_ID_INDEX = Indexes0.LOAN_ORDER_INFO_LOAN_ORDER_INFO_LOAN_ID_INDEX;
    public static final Index LOAN_ORDER_INFO_LOAN_ORDER_INFO_ORDER_IDCARDNO_INDEX = Indexes0.LOAN_ORDER_INFO_LOAN_ORDER_INFO_ORDER_IDCARDNO_INDEX;
    public static final Index LOAN_ORDER_INFO_LOAN_ORDER_INFO_ORDER_MOBILE_INDEX = Indexes0.LOAN_ORDER_INFO_LOAN_ORDER_INFO_ORDER_MOBILE_INDEX;
    public static final Index LOAN_ORDER_INFO_PRIMARY = Indexes0.LOAN_ORDER_INFO_PRIMARY;
    public static final Index MEMBER_ACCOUNT_MEMBER_ACCOUNT__INDEX_1 = Indexes0.MEMBER_ACCOUNT_MEMBER_ACCOUNT__INDEX_1;
    public static final Index MEMBER_ACCOUNT_MEMBER_ACCOUNT__INDEX_2 = Indexes0.MEMBER_ACCOUNT_MEMBER_ACCOUNT__INDEX_2;
    public static final Index MEMBER_ACCOUNT_MEMBER_AMOUNT_ID_UINDEX = Indexes0.MEMBER_ACCOUNT_MEMBER_AMOUNT_ID_UINDEX;
    public static final Index MEMBER_ACCOUNT_PRIMARY = Indexes0.MEMBER_ACCOUNT_PRIMARY;
    public static final Index MEMBER_ACCOUNT_HISTORY_MEMBER_ACCOUNT_HISTORY_INDEX_1 = Indexes0.MEMBER_ACCOUNT_HISTORY_MEMBER_ACCOUNT_HISTORY_INDEX_1;
    public static final Index MEMBER_ACCOUNT_HISTORY_MEMBER_AMOUNT_HISTROY_ID_UINDEX = Indexes0.MEMBER_ACCOUNT_HISTORY_MEMBER_AMOUNT_HISTROY_ID_UINDEX;
    public static final Index MEMBER_ACCOUNT_HISTORY_PRIMARY = Indexes0.MEMBER_ACCOUNT_HISTORY_PRIMARY;
    public static final Index MEMEBER_INFO_MEMEBER_INFO_ID_UINDEX = Indexes0.MEMEBER_INFO_MEMEBER_INFO_ID_UINDEX;
    public static final Index MEMEBER_INFO_PRIMARY = Indexes0.MEMEBER_INFO_PRIMARY;
    public static final Index MOBILE_MESSAGE_MOBILE_MESSAGE_ID_UINDEX = Indexes0.MOBILE_MESSAGE_MOBILE_MESSAGE_ID_UINDEX;
    public static final Index MOBILE_MESSAGE_PRIMARY = Indexes0.MOBILE_MESSAGE_PRIMARY;
    public static final Index POS_APPLY_PRIMARY = Indexes0.POS_APPLY_PRIMARY;
    public static final Index POS_ORDER_INFO_PRIMARY = Indexes0.POS_ORDER_INFO_PRIMARY;
    public static final Index PRODUCT_DETAIL_PRIMARY = Indexes0.PRODUCT_DETAIL_PRIMARY;
    public static final Index PRODUCT_DETAIL_PRODUCT_DETAIL_ID_UINDEX = Indexes0.PRODUCT_DETAIL_PRODUCT_DETAIL_ID_UINDEX;
    public static final Index PRODUCT_DETAIL_PARAMS_PRIMARY = Indexes0.PRODUCT_DETAIL_PARAMS_PRIMARY;
    public static final Index PRODUCT_TYPE_PRIMARY = Indexes0.PRODUCT_TYPE_PRIMARY;
    public static final Index PRODUCT_TYPE_PRODUCT_TYPE_ID_UINDEX = Indexes0.PRODUCT_TYPE_PRODUCT_TYPE_ID_UINDEX;
    public static final Index PRODUCT_TYPE_PARAMS_PRIMARY = Indexes0.PRODUCT_TYPE_PARAMS_PRIMARY;
    public static final Index SCHEDULE_JOB_PRIMARY = Indexes0.SCHEDULE_JOB_PRIMARY;
    public static final Index SCHEDULE_JOB_SCHEDULE_JOB_BEAN_NAME_INDEX = Indexes0.SCHEDULE_JOB_SCHEDULE_JOB_BEAN_NAME_INDEX;
    public static final Index SCHEDULE_JOB_SCHEDULE_JOB_JOB_ID_INDEX = Indexes0.SCHEDULE_JOB_SCHEDULE_JOB_JOB_ID_INDEX;
    public static final Index SCHEDULE_JOB_SCHEDULE_JOB_METHOD_NAME_INDEX = Indexes0.SCHEDULE_JOB_SCHEDULE_JOB_METHOD_NAME_INDEX;
    public static final Index SCHEDULE_JOB_LOG_JOB_ID = Indexes0.SCHEDULE_JOB_LOG_JOB_ID;
    public static final Index SCHEDULE_JOB_LOG_PRIMARY = Indexes0.SCHEDULE_JOB_LOG_PRIMARY;
    public static final Index SYS_CONFIG_KEY = Indexes0.SYS_CONFIG_KEY;
    public static final Index SYS_CONFIG_PRIMARY = Indexes0.SYS_CONFIG_PRIMARY;
    public static final Index SYS_LOG_PRIMARY = Indexes0.SYS_LOG_PRIMARY;
    public static final Index SYS_MENU_PRIMARY = Indexes0.SYS_MENU_PRIMARY;
    public static final Index SYS_MENU_SYS_MENU_MENU_ID_INDEX = Indexes0.SYS_MENU_SYS_MENU_MENU_ID_INDEX;
    public static final Index SYS_MENU_SYS_MENU_PARENT_ID_INDEX = Indexes0.SYS_MENU_SYS_MENU_PARENT_ID_INDEX;
    public static final Index SYS_OSS_PRIMARY = Indexes0.SYS_OSS_PRIMARY;
    public static final Index SYS_ROLE_PRIMARY = Indexes0.SYS_ROLE_PRIMARY;
    public static final Index SYS_ROLE_SYS_ROLE_ROLE_ID_INDEX = Indexes0.SYS_ROLE_SYS_ROLE_ROLE_ID_INDEX;
    public static final Index SYS_ROLE_MENU_PRIMARY = Indexes0.SYS_ROLE_MENU_PRIMARY;
    public static final Index SYS_ROLE_MENU_SYS_ROLE_MENU_MENU_ID_INDEX = Indexes0.SYS_ROLE_MENU_SYS_ROLE_MENU_MENU_ID_INDEX;
    public static final Index SYS_ROLE_MENU_SYS_ROLE_MENU_ROLE_ID_INDEX = Indexes0.SYS_ROLE_MENU_SYS_ROLE_MENU_ROLE_ID_INDEX;
    public static final Index SYS_USER_PRIMARY = Indexes0.SYS_USER_PRIMARY;
    public static final Index SYS_USER_SYS_USER_USER_ID_INDEX = Indexes0.SYS_USER_SYS_USER_USER_ID_INDEX;
    public static final Index SYS_USER_USERNAME = Indexes0.SYS_USER_USERNAME;
    public static final Index SYS_USER_ROLE_PRIMARY = Indexes0.SYS_USER_ROLE_PRIMARY;
    public static final Index SYS_USER_ROLE_SYS_USER_ROLE_ROLE_ID_INDEX = Indexes0.SYS_USER_ROLE_SYS_USER_ROLE_ROLE_ID_INDEX;
    public static final Index SYS_USER_ROLE_SYS_USER_ROLE_USER_ID_INDEX = Indexes0.SYS_USER_ROLE_SYS_USER_ROLE_USER_ID_INDEX;
    public static final Index SYS_USER_TOKEN_PRIMARY = Indexes0.SYS_USER_TOKEN_PRIMARY;
    public static final Index SYS_USER_TOKEN_TOKEN = Indexes0.SYS_USER_TOKEN_TOKEN;
    public static final Index TB_TOKEN_PRIMARY = Indexes0.TB_TOKEN_PRIMARY;
    public static final Index TB_TOKEN_TOKEN = Indexes0.TB_TOKEN_TOKEN;
    public static final Index TB_USER_PRIMARY = Indexes0.TB_USER_PRIMARY;
    public static final Index TB_USER_TB_USER_MOBILE_INDEX = Indexes0.TB_USER_TB_USER_MOBILE_INDEX;
    public static final Index TB_USER_TB_USER_USER_ID_INDEX = Indexes0.TB_USER_TB_USER_USER_ID_INDEX;
    public static final Index WITHDRAWAL_INFO_PRIMARY = Indexes0.WITHDRAWAL_INFO_PRIMARY;
    public static final Index WITHDRAWAL_INFO_WITHDRAWAL_INFO_ALIPAY_ACCOUNT_INDEX = Indexes0.WITHDRAWAL_INFO_WITHDRAWAL_INFO_ALIPAY_ACCOUNT_INDEX;
    public static final Index WITHDRAWAL_INFO_WITHDRAWAL_INFO_ID_INDEX = Indexes0.WITHDRAWAL_INFO_WITHDRAWAL_INFO_ID_INDEX;
    public static final Index WITHDRAWAL_INFO_WITHDRAWAL_INFO_WITHDRAW_MOBILE_INDEX = Indexes0.WITHDRAWAL_INFO_WITHDRAWAL_INFO_WITHDRAW_MOBILE_INDEX;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index AD_PICTURE_AD_PICTURE_ARTICLE_ID_INDEX = Internal.createIndex("ad_picture_article_id_index", AdPicture.AD_PICTURE, new OrderField[] { AdPicture.AD_PICTURE.ARTICLE_ID }, false);
        public static Index AD_PICTURE_AD_PICTURE_ID_INDEX = Internal.createIndex("ad_picture_id_index", AdPicture.AD_PICTURE, new OrderField[] { AdPicture.AD_PICTURE.ID }, false);
        public static Index AD_PICTURE_PRIMARY = Internal.createIndex("PRIMARY", AdPicture.AD_PICTURE, new OrderField[] { AdPicture.AD_PICTURE.ID }, true);
        public static Index ARTICLE_INFO_ARTICLE_INFO_ID_INDEX = Internal.createIndex("article_info_id_index", ArticleInfo.ARTICLE_INFO, new OrderField[] { ArticleInfo.ARTICLE_INFO.ID }, false);
        public static Index ARTICLE_INFO_PRIMARY = Internal.createIndex("PRIMARY", ArticleInfo.ARTICLE_INFO, new OrderField[] { ArticleInfo.ARTICLE_INFO.ID }, true);
        public static Index CARD_INFO_CARD_INFO_BANK_NUM_INDEX = Internal.createIndex("card_info_bank_num_index", CardInfo.CARD_INFO, new OrderField[] { CardInfo.CARD_INFO.BANK_NUM }, false);
        public static Index CARD_INFO_CARD_INFO_CARD_NUM_INDEX = Internal.createIndex("card_info_card_num_index", CardInfo.CARD_INFO, new OrderField[] { CardInfo.CARD_INFO.CARD_NUM }, false);
        public static Index CARD_INFO_CARD_INFO_ID_UINDEX = Internal.createIndex("card_info_id_uindex", CardInfo.CARD_INFO, new OrderField[] { CardInfo.CARD_INFO.ID }, true);
        public static Index CARD_INFO_PRIMARY = Internal.createIndex("PRIMARY", CardInfo.CARD_INFO, new OrderField[] { CardInfo.CARD_INFO.ID }, true);
        public static Index CARD_ORDER_INFO_CARD_ORDER_INFO_ID_UINDEX = Internal.createIndex("card_order_info_id_uindex", CardOrderInfo.CARD_ORDER_INFO, new OrderField[] { CardOrderInfo.CARD_ORDER_INFO.ID }, true);
        public static Index CARD_ORDER_INFO_CARD_ORDER_INFO__INDEX_1 = Internal.createIndex("card_order_info__index_1", CardOrderInfo.CARD_ORDER_INFO, new OrderField[] { CardOrderInfo.CARD_ORDER_INFO.CARD_ID }, false);
        public static Index CARD_ORDER_INFO_CARD_ORDER_INFO__INDEX_2 = Internal.createIndex("card_order_info__index_2", CardOrderInfo.CARD_ORDER_INFO, new OrderField[] { CardOrderInfo.CARD_ORDER_INFO.MEMBER_ID }, false);
        public static Index CARD_ORDER_INFO_CARD_ORDER_INFO__INDEX_3 = Internal.createIndex("card_order_info__index_3", CardOrderInfo.CARD_ORDER_INFO, new OrderField[] { CardOrderInfo.CARD_ORDER_INFO.ORDER_ID }, false);
        public static Index CARD_ORDER_INFO_PRIMARY = Internal.createIndex("PRIMARY", CardOrderInfo.CARD_ORDER_INFO, new OrderField[] { CardOrderInfo.CARD_ORDER_INFO.ID }, true);
        public static Index DISTRICT_DISTRICT_ID_INDEX = Internal.createIndex("district_id_index", District.DISTRICT, new OrderField[] { District.DISTRICT.ID }, false);
        public static Index DISTRICT_DISTRICT_PARENT_ID_INDEX = Internal.createIndex("district_parent_id_index", District.DISTRICT, new OrderField[] { District.DISTRICT.PARENT_ID }, false);
        public static Index DIS_DICTIONARY_PRIMARY = Internal.createIndex("PRIMARY", DisDictionary.DIS_DICTIONARY, new OrderField[] { DisDictionary.DIS_DICTIONARY.ID }, true);
        public static Index DIS_FANS_DIS_FANS_ID_UINDEX = Internal.createIndex("dis_fans_id_uindex", DisFans.DIS_FANS, new OrderField[] { DisFans.DIS_FANS.ID }, true);
        public static Index DIS_FANS_DIS_FANS__INDEX_1 = Internal.createIndex("dis_fans__index_1", DisFans.DIS_FANS, new OrderField[] { DisFans.DIS_FANS.WORKER_ID }, false);
        public static Index DIS_FANS_DIS_FANS__INDEX_OPENID = Internal.createIndex("dis_fans__index_openid", DisFans.DIS_FANS, new OrderField[] { DisFans.DIS_FANS.WECHAT_ID }, false);
        public static Index DIS_FANS_PRIMARY = Internal.createIndex("PRIMARY", DisFans.DIS_FANS, new OrderField[] { DisFans.DIS_FANS.ID }, true);
        public static Index DIS_MEMBER_INFO_DIS_MEMBER_INFO_ID_UINDEX = Internal.createIndex("dis_member_info_id_uindex", DisMemberInfo.DIS_MEMBER_INFO, new OrderField[] { DisMemberInfo.DIS_MEMBER_INFO.ID }, true);
        public static Index DIS_MEMBER_INFO_DIS_MEMBER_INFO__INDEX_1 = Internal.createIndex("dis_member_info__index_1", DisMemberInfo.DIS_MEMBER_INFO, new OrderField[] { DisMemberInfo.DIS_MEMBER_INFO.DIS_MODEL_ID }, false);
        public static Index DIS_MEMBER_INFO_DIS_MEMBER_INFO__INDEX_2 = Internal.createIndex("dis_member_info__index_2", DisMemberInfo.DIS_MEMBER_INFO, new OrderField[] { DisMemberInfo.DIS_MEMBER_INFO.DIS_USER_ID }, false);
        public static Index DIS_MEMBER_INFO_DIS_MEMBER_INFO__INDEX_3 = Internal.createIndex("dis_member_info__index_3", DisMemberInfo.DIS_MEMBER_INFO, new OrderField[] { DisMemberInfo.DIS_MEMBER_INFO.OPEN_ID }, false);
        public static Index DIS_MEMBER_INFO_DIS_MEMBER_INFO__INDEX_4 = Internal.createIndex("dis_member_info__index_4", DisMemberInfo.DIS_MEMBER_INFO, new OrderField[] { DisMemberInfo.DIS_MEMBER_INFO.DIS_USER_TYPE }, false);
        public static Index DIS_MEMBER_INFO_DIS_MEMBER_INFO__INDEX_5 = Internal.createIndex("dis_member_info__index_5", DisMemberInfo.DIS_MEMBER_INFO, new OrderField[] { DisMemberInfo.DIS_MEMBER_INFO.DIS_LEVEL }, false);
        public static Index DIS_MEMBER_INFO_PRIMARY = Internal.createIndex("PRIMARY", DisMemberInfo.DIS_MEMBER_INFO, new OrderField[] { DisMemberInfo.DIS_MEMBER_INFO.ID }, true);
        public static Index DIS_PROFIT_RECORD_DIS_PROFIT_RECORD_ID_UINDEX = Internal.createIndex("dis_profit_record_id_uindex", DisProfitRecord.DIS_PROFIT_RECORD, new OrderField[] { DisProfitRecord.DIS_PROFIT_RECORD.ID }, true);
        public static Index DIS_PROFIT_RECORD_PRIMARY = Internal.createIndex("PRIMARY", DisProfitRecord.DIS_PROFIT_RECORD, new OrderField[] { DisProfitRecord.DIS_PROFIT_RECORD.ID }, true);
        public static Index DIS_PROFI_PARAM_DIS_PROFI_PARAM_ID_UINDEX = Internal.createIndex("dis_profi_param_id_uindex", DisProfiParam.DIS_PROFI_PARAM, new OrderField[] { DisProfiParam.DIS_PROFI_PARAM.ID }, true);
        public static Index DIS_PROFI_PARAM_PRIMARY = Internal.createIndex("PRIMARY", DisProfiParam.DIS_PROFI_PARAM, new OrderField[] { DisProfiParam.DIS_PROFI_PARAM.ID }, true);
        public static Index FEEDBACK_FEEDBACK_ID_INDEX = Internal.createIndex("feedback_id_index", Feedback.FEEDBACK, new OrderField[] { Feedback.FEEDBACK.ID }, false);
        public static Index FEEDBACK_FEEDBACK_MEMBER_ID_INDEX = Internal.createIndex("feedback_member_id_index", Feedback.FEEDBACK, new OrderField[] { Feedback.FEEDBACK.MEMBER_ID }, false);
        public static Index FEEDBACK_PRIMARY = Internal.createIndex("PRIMARY", Feedback.FEEDBACK, new OrderField[] { Feedback.FEEDBACK.ID }, true);
        public static Index INTEGRAL_ORDER_INTEGRAL_ORDER_DETAIL_ID_INDEX = Internal.createIndex("integral_order_detail_id_index", IntegralOrder.INTEGRAL_ORDER, new OrderField[] { IntegralOrder.INTEGRAL_ORDER.DETAIL_ID }, false);
        public static Index INTEGRAL_ORDER_INTEGRAL_ORDER_ID_UINDEX = Internal.createIndex("integral_order_id_uindex", IntegralOrder.INTEGRAL_ORDER, new OrderField[] { IntegralOrder.INTEGRAL_ORDER.ID }, true);
        public static Index INTEGRAL_ORDER_INTEGRAL_ORDER_MOBILE_INDEX = Internal.createIndex("integral_order_mobile_index", IntegralOrder.INTEGRAL_ORDER, new OrderField[] { IntegralOrder.INTEGRAL_ORDER.MOBILE }, false);
        public static Index INTEGRAL_ORDER_PRIMARY = Internal.createIndex("PRIMARY", IntegralOrder.INTEGRAL_ORDER, new OrderField[] { IntegralOrder.INTEGRAL_ORDER.ID }, true);
        public static Index INTEGRAL_TUTORIAL_PRIMARY = Internal.createIndex("PRIMARY", IntegralTutorial.INTEGRAL_TUTORIAL, new OrderField[] { IntegralTutorial.INTEGRAL_TUTORIAL.ID }, true);
        public static Index LOAN_INFO_LOAN_INFO_ID_UINDEX = Internal.createIndex("loan_info_id_uindex", LoanInfo.LOAN_INFO, new OrderField[] { LoanInfo.LOAN_INFO.ID }, true);
        public static Index LOAN_INFO_PRIMARY = Internal.createIndex("PRIMARY", LoanInfo.LOAN_INFO, new OrderField[] { LoanInfo.LOAN_INFO.ID }, true);
        public static Index LOAN_ORDER_INFO_LOAN_ORDER_INFO_ID_UINDEX = Internal.createIndex("loan_order_info_id_uindex", LoanOrderInfo.LOAN_ORDER_INFO, new OrderField[] { LoanOrderInfo.LOAN_ORDER_INFO.ID }, true);
        public static Index LOAN_ORDER_INFO_LOAN_ORDER_INFO_LOAN_ID_INDEX = Internal.createIndex("loan_order_info_loan_id_index", LoanOrderInfo.LOAN_ORDER_INFO, new OrderField[] { LoanOrderInfo.LOAN_ORDER_INFO.LOAN_ID }, false);
        public static Index LOAN_ORDER_INFO_LOAN_ORDER_INFO_ORDER_IDCARDNO_INDEX = Internal.createIndex("loan_order_info_order_idcardno_index", LoanOrderInfo.LOAN_ORDER_INFO, new OrderField[] { LoanOrderInfo.LOAN_ORDER_INFO.ORDER_IDCARDNO }, false);
        public static Index LOAN_ORDER_INFO_LOAN_ORDER_INFO_ORDER_MOBILE_INDEX = Internal.createIndex("loan_order_info_order_mobile_index", LoanOrderInfo.LOAN_ORDER_INFO, new OrderField[] { LoanOrderInfo.LOAN_ORDER_INFO.ORDER_MOBILE }, false);
        public static Index LOAN_ORDER_INFO_PRIMARY = Internal.createIndex("PRIMARY", LoanOrderInfo.LOAN_ORDER_INFO, new OrderField[] { LoanOrderInfo.LOAN_ORDER_INFO.ID }, true);
        public static Index MEMBER_ACCOUNT_MEMBER_ACCOUNT__INDEX_1 = Internal.createIndex("member_account__index_1", MemberAccount.MEMBER_ACCOUNT, new OrderField[] { MemberAccount.MEMBER_ACCOUNT.MEMBER_ID }, false);
        public static Index MEMBER_ACCOUNT_MEMBER_ACCOUNT__INDEX_2 = Internal.createIndex("member_account__index_2", MemberAccount.MEMBER_ACCOUNT, new OrderField[] { MemberAccount.MEMBER_ACCOUNT.ALIPAY_ACCOUNT }, false);
        public static Index MEMBER_ACCOUNT_MEMBER_AMOUNT_ID_UINDEX = Internal.createIndex("member_amount_id_uindex", MemberAccount.MEMBER_ACCOUNT, new OrderField[] { MemberAccount.MEMBER_ACCOUNT.ACCOUNT_ID }, true);
        public static Index MEMBER_ACCOUNT_PRIMARY = Internal.createIndex("PRIMARY", MemberAccount.MEMBER_ACCOUNT, new OrderField[] { MemberAccount.MEMBER_ACCOUNT.ACCOUNT_ID }, true);
        public static Index MEMBER_ACCOUNT_HISTORY_MEMBER_ACCOUNT_HISTORY_INDEX_1 = Internal.createIndex("member_account_history_index_1", MemberAccountHistory.MEMBER_ACCOUNT_HISTORY, new OrderField[] { MemberAccountHistory.MEMBER_ACCOUNT_HISTORY.ACCOUNT_ID }, false);
        public static Index MEMBER_ACCOUNT_HISTORY_MEMBER_AMOUNT_HISTROY_ID_UINDEX = Internal.createIndex("member_amount_histroy_id_uindex", MemberAccountHistory.MEMBER_ACCOUNT_HISTORY, new OrderField[] { MemberAccountHistory.MEMBER_ACCOUNT_HISTORY.ID }, true);
        public static Index MEMBER_ACCOUNT_HISTORY_PRIMARY = Internal.createIndex("PRIMARY", MemberAccountHistory.MEMBER_ACCOUNT_HISTORY, new OrderField[] { MemberAccountHistory.MEMBER_ACCOUNT_HISTORY.ID }, true);
        public static Index MEMEBER_INFO_MEMEBER_INFO_ID_UINDEX = Internal.createIndex("memeber_info_id_uindex", MemeberInfo.MEMEBER_INFO, new OrderField[] { MemeberInfo.MEMEBER_INFO.ID }, true);
        public static Index MEMEBER_INFO_PRIMARY = Internal.createIndex("PRIMARY", MemeberInfo.MEMEBER_INFO, new OrderField[] { MemeberInfo.MEMEBER_INFO.ID }, true);
        public static Index MOBILE_MESSAGE_MOBILE_MESSAGE_ID_UINDEX = Internal.createIndex("mobile_message_id_uindex", MobileMessage.MOBILE_MESSAGE, new OrderField[] { MobileMessage.MOBILE_MESSAGE.ID }, true);
        public static Index MOBILE_MESSAGE_PRIMARY = Internal.createIndex("PRIMARY", MobileMessage.MOBILE_MESSAGE, new OrderField[] { MobileMessage.MOBILE_MESSAGE.ID }, true);
        public static Index POS_APPLY_PRIMARY = Internal.createIndex("PRIMARY", PosApply.POS_APPLY, new OrderField[] { PosApply.POS_APPLY.ID }, true);
        public static Index POS_ORDER_INFO_PRIMARY = Internal.createIndex("PRIMARY", PosOrderInfo.POS_ORDER_INFO, new OrderField[] { PosOrderInfo.POS_ORDER_INFO.ID }, true);
        public static Index PRODUCT_DETAIL_PRIMARY = Internal.createIndex("PRIMARY", ProductDetail.PRODUCT_DETAIL, new OrderField[] { ProductDetail.PRODUCT_DETAIL.ID }, true);
        public static Index PRODUCT_DETAIL_PRODUCT_DETAIL_ID_UINDEX = Internal.createIndex("product_detail_id_uindex", ProductDetail.PRODUCT_DETAIL, new OrderField[] { ProductDetail.PRODUCT_DETAIL.ID }, true);
        public static Index PRODUCT_DETAIL_PARAMS_PRIMARY = Internal.createIndex("PRIMARY", ProductDetailParams.PRODUCT_DETAIL_PARAMS, new OrderField[] { ProductDetailParams.PRODUCT_DETAIL_PARAMS.ID }, true);
        public static Index PRODUCT_TYPE_PRIMARY = Internal.createIndex("PRIMARY", ProductType.PRODUCT_TYPE, new OrderField[] { ProductType.PRODUCT_TYPE.ID }, true);
        public static Index PRODUCT_TYPE_PRODUCT_TYPE_ID_UINDEX = Internal.createIndex("product_type_id_uindex", ProductType.PRODUCT_TYPE, new OrderField[] { ProductType.PRODUCT_TYPE.ID }, true);
        public static Index PRODUCT_TYPE_PARAMS_PRIMARY = Internal.createIndex("PRIMARY", ProductTypeParams.PRODUCT_TYPE_PARAMS, new OrderField[] { ProductTypeParams.PRODUCT_TYPE_PARAMS.ID }, true);
        public static Index SCHEDULE_JOB_PRIMARY = Internal.createIndex("PRIMARY", ScheduleJob.SCHEDULE_JOB, new OrderField[] { ScheduleJob.SCHEDULE_JOB.JOB_ID }, true);
        public static Index SCHEDULE_JOB_SCHEDULE_JOB_BEAN_NAME_INDEX = Internal.createIndex("schedule_job_bean_name_index", ScheduleJob.SCHEDULE_JOB, new OrderField[] { ScheduleJob.SCHEDULE_JOB.BEAN_NAME }, false);
        public static Index SCHEDULE_JOB_SCHEDULE_JOB_JOB_ID_INDEX = Internal.createIndex("schedule_job_job_id_index", ScheduleJob.SCHEDULE_JOB, new OrderField[] { ScheduleJob.SCHEDULE_JOB.JOB_ID }, false);
        public static Index SCHEDULE_JOB_SCHEDULE_JOB_METHOD_NAME_INDEX = Internal.createIndex("schedule_job_method_name_index", ScheduleJob.SCHEDULE_JOB, new OrderField[] { ScheduleJob.SCHEDULE_JOB.METHOD_NAME }, false);
        public static Index SCHEDULE_JOB_LOG_JOB_ID = Internal.createIndex("job_id", ScheduleJobLog.SCHEDULE_JOB_LOG, new OrderField[] { ScheduleJobLog.SCHEDULE_JOB_LOG.JOB_ID }, false);
        public static Index SCHEDULE_JOB_LOG_PRIMARY = Internal.createIndex("PRIMARY", ScheduleJobLog.SCHEDULE_JOB_LOG, new OrderField[] { ScheduleJobLog.SCHEDULE_JOB_LOG.LOG_ID }, true);
        public static Index SYS_CONFIG_KEY = Internal.createIndex("key", SysConfig.SYS_CONFIG, new OrderField[] { SysConfig.SYS_CONFIG.KEY }, true);
        public static Index SYS_CONFIG_PRIMARY = Internal.createIndex("PRIMARY", SysConfig.SYS_CONFIG, new OrderField[] { SysConfig.SYS_CONFIG.ID }, true);
        public static Index SYS_LOG_PRIMARY = Internal.createIndex("PRIMARY", SysLog.SYS_LOG, new OrderField[] { SysLog.SYS_LOG.ID }, true);
        public static Index SYS_MENU_PRIMARY = Internal.createIndex("PRIMARY", SysMenu.SYS_MENU, new OrderField[] { SysMenu.SYS_MENU.MENU_ID }, true);
        public static Index SYS_MENU_SYS_MENU_MENU_ID_INDEX = Internal.createIndex("sys_menu_menu_id_index", SysMenu.SYS_MENU, new OrderField[] { SysMenu.SYS_MENU.MENU_ID }, false);
        public static Index SYS_MENU_SYS_MENU_PARENT_ID_INDEX = Internal.createIndex("sys_menu_parent_id_index", SysMenu.SYS_MENU, new OrderField[] { SysMenu.SYS_MENU.PARENT_ID }, false);
        public static Index SYS_OSS_PRIMARY = Internal.createIndex("PRIMARY", SysOss.SYS_OSS, new OrderField[] { SysOss.SYS_OSS.ID }, true);
        public static Index SYS_ROLE_PRIMARY = Internal.createIndex("PRIMARY", SysRole.SYS_ROLE, new OrderField[] { SysRole.SYS_ROLE.ROLE_ID }, true);
        public static Index SYS_ROLE_SYS_ROLE_ROLE_ID_INDEX = Internal.createIndex("sys_role_role_id_index", SysRole.SYS_ROLE, new OrderField[] { SysRole.SYS_ROLE.ROLE_ID }, false);
        public static Index SYS_ROLE_MENU_PRIMARY = Internal.createIndex("PRIMARY", SysRoleMenu.SYS_ROLE_MENU, new OrderField[] { SysRoleMenu.SYS_ROLE_MENU.ID }, true);
        public static Index SYS_ROLE_MENU_SYS_ROLE_MENU_MENU_ID_INDEX = Internal.createIndex("sys_role_menu_menu_id_index", SysRoleMenu.SYS_ROLE_MENU, new OrderField[] { SysRoleMenu.SYS_ROLE_MENU.MENU_ID }, false);
        public static Index SYS_ROLE_MENU_SYS_ROLE_MENU_ROLE_ID_INDEX = Internal.createIndex("sys_role_menu_role_id_index", SysRoleMenu.SYS_ROLE_MENU, new OrderField[] { SysRoleMenu.SYS_ROLE_MENU.ROLE_ID }, false);
        public static Index SYS_USER_PRIMARY = Internal.createIndex("PRIMARY", SysUser.SYS_USER, new OrderField[] { SysUser.SYS_USER.USER_ID }, true);
        public static Index SYS_USER_SYS_USER_USER_ID_INDEX = Internal.createIndex("sys_user_user_id_index", SysUser.SYS_USER, new OrderField[] { SysUser.SYS_USER.USER_ID }, false);
        public static Index SYS_USER_USERNAME = Internal.createIndex("username", SysUser.SYS_USER, new OrderField[] { SysUser.SYS_USER.USERNAME }, true);
        public static Index SYS_USER_ROLE_PRIMARY = Internal.createIndex("PRIMARY", SysUserRole.SYS_USER_ROLE, new OrderField[] { SysUserRole.SYS_USER_ROLE.ID }, true);
        public static Index SYS_USER_ROLE_SYS_USER_ROLE_ROLE_ID_INDEX = Internal.createIndex("sys_user_role_role_id_index", SysUserRole.SYS_USER_ROLE, new OrderField[] { SysUserRole.SYS_USER_ROLE.ROLE_ID }, false);
        public static Index SYS_USER_ROLE_SYS_USER_ROLE_USER_ID_INDEX = Internal.createIndex("sys_user_role_user_id_index", SysUserRole.SYS_USER_ROLE, new OrderField[] { SysUserRole.SYS_USER_ROLE.USER_ID }, false);
        public static Index SYS_USER_TOKEN_PRIMARY = Internal.createIndex("PRIMARY", SysUserToken.SYS_USER_TOKEN, new OrderField[] { SysUserToken.SYS_USER_TOKEN.USER_ID }, true);
        public static Index SYS_USER_TOKEN_TOKEN = Internal.createIndex("token", SysUserToken.SYS_USER_TOKEN, new OrderField[] { SysUserToken.SYS_USER_TOKEN.TOKEN }, true);
        public static Index TB_TOKEN_PRIMARY = Internal.createIndex("PRIMARY", TbToken.TB_TOKEN, new OrderField[] { TbToken.TB_TOKEN.USER_ID }, true);
        public static Index TB_TOKEN_TOKEN = Internal.createIndex("token", TbToken.TB_TOKEN, new OrderField[] { TbToken.TB_TOKEN.TOKEN }, true);
        public static Index TB_USER_PRIMARY = Internal.createIndex("PRIMARY", TbUser.TB_USER, new OrderField[] { TbUser.TB_USER.USER_ID }, true);
        public static Index TB_USER_TB_USER_MOBILE_INDEX = Internal.createIndex("tb_user_mobile_index", TbUser.TB_USER, new OrderField[] { TbUser.TB_USER.MOBILE }, false);
        public static Index TB_USER_TB_USER_USER_ID_INDEX = Internal.createIndex("tb_user_user_id_index", TbUser.TB_USER, new OrderField[] { TbUser.TB_USER.USER_ID }, false);
        public static Index WITHDRAWAL_INFO_PRIMARY = Internal.createIndex("PRIMARY", WithdrawalInfo.WITHDRAWAL_INFO, new OrderField[] { WithdrawalInfo.WITHDRAWAL_INFO.ID }, true);
        public static Index WITHDRAWAL_INFO_WITHDRAWAL_INFO_ALIPAY_ACCOUNT_INDEX = Internal.createIndex("withdrawal_info_alipay_account_index", WithdrawalInfo.WITHDRAWAL_INFO, new OrderField[] { WithdrawalInfo.WITHDRAWAL_INFO.ALIPAY_ACCOUNT }, false);
        public static Index WITHDRAWAL_INFO_WITHDRAWAL_INFO_ID_INDEX = Internal.createIndex("withdrawal_info_id_index", WithdrawalInfo.WITHDRAWAL_INFO, new OrderField[] { WithdrawalInfo.WITHDRAWAL_INFO.ID }, false);
        public static Index WITHDRAWAL_INFO_WITHDRAWAL_INFO_WITHDRAW_MOBILE_INDEX = Internal.createIndex("withdrawal_info_withdraw_mobile_index", WithdrawalInfo.WITHDRAWAL_INFO, new OrderField[] { WithdrawalInfo.WITHDRAWAL_INFO.WITHDRAW_MOBILE }, false);
    }
}
