/*
 * This file is generated by jOOQ.
*/
package com.distribution.pojo.tables.pojos;


import javax.annotation.Generated;
import java.io.Serializable;


/**
 * 可办信用卡信息表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CardInfo implements Serializable {

    private static final long serialVersionUID = 1960580532;

    private String  id;
    private String  bankNum;
    private String  cardNum;
    private String  cardName;
    private String  cardImg;
    private String  cardInfo;
    private String  cardUrl;
    private String  updateTime;
    private String  addTime;
    private String  isDelete;
    private Double  rebate;
    private Integer useThirdPart;

    public CardInfo() {}

    public CardInfo(CardInfo value) {
        this.id = value.id;
        this.bankNum = value.bankNum;
        this.cardNum = value.cardNum;
        this.cardName = value.cardName;
        this.cardImg = value.cardImg;
        this.cardInfo = value.cardInfo;
        this.cardUrl = value.cardUrl;
        this.updateTime = value.updateTime;
        this.addTime = value.addTime;
        this.isDelete = value.isDelete;
        this.rebate = value.rebate;
        this.useThirdPart = value.useThirdPart;
    }

    public CardInfo(
        String  id,
        String  bankNum,
        String  cardNum,
        String  cardName,
        String  cardImg,
        String  cardInfo,
        String  cardUrl,
        String  updateTime,
        String  addTime,
        String  isDelete,
        Double  rebate,
        Integer useThirdPart
    ) {
        this.id = id;
        this.bankNum = bankNum;
        this.cardNum = cardNum;
        this.cardName = cardName;
        this.cardImg = cardImg;
        this.cardInfo = cardInfo;
        this.cardUrl = cardUrl;
        this.updateTime = updateTime;
        this.addTime = addTime;
        this.isDelete = isDelete;
        this.rebate = rebate;
        this.useThirdPart = useThirdPart;
    }

    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getBankNum() {
        return this.bankNum;
    }

    public void setBankNum(String bankNum) {
        this.bankNum = bankNum;
    }

    public String getCardNum() {
        return this.cardNum;
    }

    public void setCardNum(String cardNum) {
        this.cardNum = cardNum;
    }

    public String getCardName() {
        return this.cardName;
    }

    public void setCardName(String cardName) {
        this.cardName = cardName;
    }

    public String getCardImg() {
        return this.cardImg;
    }

    public void setCardImg(String cardImg) {
        this.cardImg = cardImg;
    }

    public String getCardInfo() {
        return this.cardInfo;
    }

    public void setCardInfo(String cardInfo) {
        this.cardInfo = cardInfo;
    }

    public String getCardUrl() {
        return this.cardUrl;
    }

    public void setCardUrl(String cardUrl) {
        this.cardUrl = cardUrl;
    }

    public String getUpdateTime() {
        return this.updateTime;
    }

    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime;
    }

    public String getAddTime() {
        return this.addTime;
    }

    public void setAddTime(String addTime) {
        this.addTime = addTime;
    }

    public String getIsDelete() {
        return this.isDelete;
    }

    public void setIsDelete(String isDelete) {
        this.isDelete = isDelete;
    }

    public Double getRebate() {
        return this.rebate;
    }

    public void setRebate(Double rebate) {
        this.rebate = rebate;
    }

    public Integer getUseThirdPart() {
        return this.useThirdPart;
    }

    public void setUseThirdPart(Integer useThirdPart) {
        this.useThirdPart = useThirdPart;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("CardInfo (");

        sb.append(id);
        sb.append(", ").append(bankNum);
        sb.append(", ").append(cardNum);
        sb.append(", ").append(cardName);
        sb.append(", ").append(cardImg);
        sb.append(", ").append(cardInfo);
        sb.append(", ").append(cardUrl);
        sb.append(", ").append(updateTime);
        sb.append(", ").append(addTime);
        sb.append(", ").append(isDelete);
        sb.append(", ").append(rebate);
        sb.append(", ").append(useThirdPart);

        sb.append(")");
        return sb.toString();
    }
}
