/*
 * This file is generated by jOOQ.
*/
package com.distribution.pojo.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * 会员信息表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MemeberInfo implements Serializable {

    private static final long serialVersionUID = -740689349;

    private String id;
    private String memberCode;
    private String openId;
    private String memberName;
    private String memberPwd;
    private String memberSource;
    private String isDelete;
    private String addTime;
    private String updateTime;

    public MemeberInfo() {}

    public MemeberInfo(MemeberInfo value) {
        this.id = value.id;
        this.memberCode = value.memberCode;
        this.openId = value.openId;
        this.memberName = value.memberName;
        this.memberPwd = value.memberPwd;
        this.memberSource = value.memberSource;
        this.isDelete = value.isDelete;
        this.addTime = value.addTime;
        this.updateTime = value.updateTime;
    }

    public MemeberInfo(
        String id,
        String memberCode,
        String openId,
        String memberName,
        String memberPwd,
        String memberSource,
        String isDelete,
        String addTime,
        String updateTime
    ) {
        this.id = id;
        this.memberCode = memberCode;
        this.openId = openId;
        this.memberName = memberName;
        this.memberPwd = memberPwd;
        this.memberSource = memberSource;
        this.isDelete = isDelete;
        this.addTime = addTime;
        this.updateTime = updateTime;
    }

    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getMemberCode() {
        return this.memberCode;
    }

    public void setMemberCode(String memberCode) {
        this.memberCode = memberCode;
    }

    public String getOpenId() {
        return this.openId;
    }

    public void setOpenId(String openId) {
        this.openId = openId;
    }

    public String getMemberName() {
        return this.memberName;
    }

    public void setMemberName(String memberName) {
        this.memberName = memberName;
    }

    public String getMemberPwd() {
        return this.memberPwd;
    }

    public void setMemberPwd(String memberPwd) {
        this.memberPwd = memberPwd;
    }

    public String getMemberSource() {
        return this.memberSource;
    }

    public void setMemberSource(String memberSource) {
        this.memberSource = memberSource;
    }

    public String getIsDelete() {
        return this.isDelete;
    }

    public void setIsDelete(String isDelete) {
        this.isDelete = isDelete;
    }

    public String getAddTime() {
        return this.addTime;
    }

    public void setAddTime(String addTime) {
        this.addTime = addTime;
    }

    public String getUpdateTime() {
        return this.updateTime;
    }

    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("MemeberInfo (");

        sb.append(id);
        sb.append(", ").append(memberCode);
        sb.append(", ").append(openId);
        sb.append(", ").append(memberName);
        sb.append(", ").append(memberPwd);
        sb.append(", ").append(memberSource);
        sb.append(", ").append(isDelete);
        sb.append(", ").append(addTime);
        sb.append(", ").append(updateTime);

        sb.append(")");
        return sb.toString();
    }
}
