/*
 * This file is generated by jOOQ.
*/
package com.distribution.pojo.tables.pojos;


import javax.annotation.Generated;
import java.io.Serializable;


/**
 * POS机申请表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PosApply implements Serializable {

    private static final long serialVersionUID = 398335998;

    private String  id;
    private String  name;
    private Long    mobile;
    private String  merchants;
    private String  areaCode;
    private Boolean attribute;
    private String  addTime;
    private String  isDelete;

    public PosApply() {}

    public PosApply(PosApply value) {
        this.id = value.id;
        this.name = value.name;
        this.mobile = value.mobile;
        this.merchants = value.merchants;
        this.areaCode = value.areaCode;
        this.attribute = value.attribute;
        this.addTime = value.addTime;
        this.isDelete = value.isDelete;
    }

    public PosApply(
        String  id,
        String  name,
        Long    mobile,
        String  merchants,
        String  areaCode,
        Boolean attribute,
        String  addTime,
        String  isDelete
    ) {
        this.id = id;
        this.name = name;
        this.mobile = mobile;
        this.merchants = merchants;
        this.areaCode = areaCode;
        this.attribute = attribute;
        this.addTime = addTime;
        this.isDelete = isDelete;
    }

    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Long getMobile() {
        return this.mobile;
    }

    public void setMobile(Long mobile) {
        this.mobile = mobile;
    }

    public String getMerchants() {
        return this.merchants;
    }

    public void setMerchants(String merchants) {
        this.merchants = merchants;
    }

    public String getAreaCode() {
        return this.areaCode;
    }

    public void setAreaCode(String areaCode) {
        this.areaCode = areaCode;
    }

    public Boolean getAttribute() {
        return this.attribute;
    }

    public void setAttribute(Boolean attribute) {
        this.attribute = attribute;
    }

    public String getAddTime() {
        return this.addTime;
    }

    public void setAddTime(String addTime) {
        this.addTime = addTime;
    }

    public String getIsDelete() {
        return this.isDelete;
    }

    public void setIsDelete(String isDelete) {
        this.isDelete = isDelete;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("PosApply (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(mobile);
        sb.append(", ").append(merchants);
        sb.append(", ").append(areaCode);
        sb.append(", ").append(attribute);
        sb.append(", ").append(addTime);
        sb.append(", ").append(isDelete);

        sb.append(")");
        return sb.toString();
    }
}
