/*
 * This file is generated by jOOQ.
*/
package com.distribution.pojo.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * ????
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ScheduleJob implements Serializable {

    private static final long serialVersionUID = -115723548;

    private Long      jobId;
    private String    beanName;
    private String    methodName;
    private String    params;
    private String    cronExpression;
    private Boolean   status;
    private String    remark;
    private Timestamp createTime;

    public ScheduleJob() {}

    public ScheduleJob(ScheduleJob value) {
        this.jobId = value.jobId;
        this.beanName = value.beanName;
        this.methodName = value.methodName;
        this.params = value.params;
        this.cronExpression = value.cronExpression;
        this.status = value.status;
        this.remark = value.remark;
        this.createTime = value.createTime;
    }

    public ScheduleJob(
        Long      jobId,
        String    beanName,
        String    methodName,
        String    params,
        String    cronExpression,
        Boolean   status,
        String    remark,
        Timestamp createTime
    ) {
        this.jobId = jobId;
        this.beanName = beanName;
        this.methodName = methodName;
        this.params = params;
        this.cronExpression = cronExpression;
        this.status = status;
        this.remark = remark;
        this.createTime = createTime;
    }

    public Long getJobId() {
        return this.jobId;
    }

    public void setJobId(Long jobId) {
        this.jobId = jobId;
    }

    public String getBeanName() {
        return this.beanName;
    }

    public void setBeanName(String beanName) {
        this.beanName = beanName;
    }

    public String getMethodName() {
        return this.methodName;
    }

    public void setMethodName(String methodName) {
        this.methodName = methodName;
    }

    public String getParams() {
        return this.params;
    }

    public void setParams(String params) {
        this.params = params;
    }

    public String getCronExpression() {
        return this.cronExpression;
    }

    public void setCronExpression(String cronExpression) {
        this.cronExpression = cronExpression;
    }

    public Boolean getStatus() {
        return this.status;
    }

    public void setStatus(Boolean status) {
        this.status = status;
    }

    public String getRemark() {
        return this.remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    public Timestamp getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Timestamp createTime) {
        this.createTime = createTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ScheduleJob (");

        sb.append(jobId);
        sb.append(", ").append(beanName);
        sb.append(", ").append(methodName);
        sb.append(", ").append(params);
        sb.append(", ").append(cronExpression);
        sb.append(", ").append(status);
        sb.append(", ").append(remark);
        sb.append(", ").append(createTime);

        sb.append(")");
        return sb.toString();
    }
}
