/*
 * This file is generated by jOOQ.
*/
package com.distribution.pojo.tables.records;


import com.distribution.pojo.tables.MemeberInfo;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 会员信息表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MemeberInfoRecord extends UpdatableRecordImpl<MemeberInfoRecord> implements Record9<String, String, String, String, String, String, String, String, String> {

    private static final long serialVersionUID = 831144711;

    /**
     * Setter for <code>distribution.memeber_info.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>distribution.memeber_info.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>distribution.memeber_info.member_code</code>.
     */
    public void setMemberCode(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>distribution.memeber_info.member_code</code>.
     */
    public String getMemberCode() {
        return (String) get(1);
    }

    /**
     * Setter for <code>distribution.memeber_info.open_id</code>.
     */
    public void setOpenId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>distribution.memeber_info.open_id</code>.
     */
    public String getOpenId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>distribution.memeber_info.member_name</code>.
     */
    public void setMemberName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>distribution.memeber_info.member_name</code>.
     */
    public String getMemberName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>distribution.memeber_info.member_pwd</code>.
     */
    public void setMemberPwd(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>distribution.memeber_info.member_pwd</code>.
     */
    public String getMemberPwd() {
        return (String) get(4);
    }

    /**
     * Setter for <code>distribution.memeber_info.member_source</code>.
     */
    public void setMemberSource(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>distribution.memeber_info.member_source</code>.
     */
    public String getMemberSource() {
        return (String) get(5);
    }

    /**
     * Setter for <code>distribution.memeber_info.is_delete</code>.
     */
    public void setIsDelete(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>distribution.memeber_info.is_delete</code>.
     */
    public String getIsDelete() {
        return (String) get(6);
    }

    /**
     * Setter for <code>distribution.memeber_info.add_time</code>.
     */
    public void setAddTime(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>distribution.memeber_info.add_time</code>.
     */
    public String getAddTime() {
        return (String) get(7);
    }

    /**
     * Setter for <code>distribution.memeber_info.update_time</code>.
     */
    public void setUpdateTime(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>distribution.memeber_info.update_time</code>.
     */
    public String getUpdateTime() {
        return (String) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<String, String, String, String, String, String, String, String, String> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<String, String, String, String, String, String, String, String, String> valuesRow() {
        return (Row9) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return MemeberInfo.MEMEBER_INFO.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return MemeberInfo.MEMEBER_INFO.MEMBER_CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return MemeberInfo.MEMEBER_INFO.OPEN_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return MemeberInfo.MEMEBER_INFO.MEMBER_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return MemeberInfo.MEMEBER_INFO.MEMBER_PWD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return MemeberInfo.MEMEBER_INFO.MEMBER_SOURCE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return MemeberInfo.MEMEBER_INFO.IS_DELETE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return MemeberInfo.MEMEBER_INFO.ADD_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return MemeberInfo.MEMEBER_INFO.UPDATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getMemberCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getOpenId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getMemberName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getMemberPwd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getMemberSource();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getIsDelete();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getAddTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getMemberCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getOpenId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getMemberName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getMemberPwd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getMemberSource();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getIsDelete();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getAddTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MemeberInfoRecord value1(String value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MemeberInfoRecord value2(String value) {
        setMemberCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MemeberInfoRecord value3(String value) {
        setOpenId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MemeberInfoRecord value4(String value) {
        setMemberName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MemeberInfoRecord value5(String value) {
        setMemberPwd(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MemeberInfoRecord value6(String value) {
        setMemberSource(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MemeberInfoRecord value7(String value) {
        setIsDelete(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MemeberInfoRecord value8(String value) {
        setAddTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MemeberInfoRecord value9(String value) {
        setUpdateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MemeberInfoRecord values(String value1, String value2, String value3, String value4, String value5, String value6, String value7, String value8, String value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MemeberInfoRecord
     */
    public MemeberInfoRecord() {
        super(MemeberInfo.MEMEBER_INFO);
    }

    /**
     * Create a detached, initialised MemeberInfoRecord
     */
    public MemeberInfoRecord(String id, String memberCode, String openId, String memberName, String memberPwd, String memberSource, String isDelete, String addTime, String updateTime) {
        super(MemeberInfo.MEMEBER_INFO);

        set(0, id);
        set(1, memberCode);
        set(2, openId);
        set(3, memberName);
        set(4, memberPwd);
        set(5, memberSource);
        set(6, isDelete);
        set(7, addTime);
        set(8, updateTime);
    }
}
