/*
 * This file is generated by jOOQ.
*/
package com.distribution.pojo.tables.records;


import com.distribution.pojo.tables.MobileMessage;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 发送短信信息表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MobileMessageRecord extends UpdatableRecordImpl<MobileMessageRecord> implements Record8<String, String, String, String, Integer, String, String, String> {

    private static final long serialVersionUID = 1934459044;

    /**
     * Setter for <code>distribution.mobile_message.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>distribution.mobile_message.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>distribution.mobile_message.mobile</code>.
     */
    public void setMobile(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>distribution.mobile_message.mobile</code>.
     */
    public String getMobile() {
        return (String) get(1);
    }

    /**
     * Setter for <code>distribution.mobile_message.code</code>.
     */
    public void setCode(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>distribution.mobile_message.code</code>.
     */
    public String getCode() {
        return (String) get(2);
    }

    /**
     * Setter for <code>distribution.mobile_message.send_time</code>.
     */
    public void setSendTime(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>distribution.mobile_message.send_time</code>.
     */
    public String getSendTime() {
        return (String) get(3);
    }

    /**
     * Setter for <code>distribution.mobile_message.count</code>.
     */
    public void setCount(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>distribution.mobile_message.count</code>.
     */
    public Integer getCount() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>distribution.mobile_message.add_time</code>.
     */
    public void setAddTime(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>distribution.mobile_message.add_time</code>.
     */
    public String getAddTime() {
        return (String) get(5);
    }

    /**
     * Setter for <code>distribution.mobile_message.is_delete</code>.
     */
    public void setIsDelete(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>distribution.mobile_message.is_delete</code>.
     */
    public String getIsDelete() {
        return (String) get(6);
    }

    /**
     * Setter for <code>distribution.mobile_message.update_time</code>.
     */
    public void setUpdateTime(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>distribution.mobile_message.update_time</code>.
     */
    public String getUpdateTime() {
        return (String) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<String, String, String, String, Integer, String, String, String> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<String, String, String, String, Integer, String, String, String> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return MobileMessage.MOBILE_MESSAGE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return MobileMessage.MOBILE_MESSAGE.MOBILE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return MobileMessage.MOBILE_MESSAGE.CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return MobileMessage.MOBILE_MESSAGE.SEND_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return MobileMessage.MOBILE_MESSAGE.COUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return MobileMessage.MOBILE_MESSAGE.ADD_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return MobileMessage.MOBILE_MESSAGE.IS_DELETE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return MobileMessage.MOBILE_MESSAGE.UPDATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getMobile();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getSendTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component5() {
        return getCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getAddTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getIsDelete();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getMobile();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getSendTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getAddTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getIsDelete();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MobileMessageRecord value1(String value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MobileMessageRecord value2(String value) {
        setMobile(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MobileMessageRecord value3(String value) {
        setCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MobileMessageRecord value4(String value) {
        setSendTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MobileMessageRecord value5(Integer value) {
        setCount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MobileMessageRecord value6(String value) {
        setAddTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MobileMessageRecord value7(String value) {
        setIsDelete(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MobileMessageRecord value8(String value) {
        setUpdateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MobileMessageRecord values(String value1, String value2, String value3, String value4, Integer value5, String value6, String value7, String value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MobileMessageRecord
     */
    public MobileMessageRecord() {
        super(MobileMessage.MOBILE_MESSAGE);
    }

    /**
     * Create a detached, initialised MobileMessageRecord
     */
    public MobileMessageRecord(String id, String mobile, String code, String sendTime, Integer count, String addTime, String isDelete, String updateTime) {
        super(MobileMessage.MOBILE_MESSAGE);

        set(0, id);
        set(1, mobile);
        set(2, code);
        set(3, sendTime);
        set(4, count);
        set(5, addTime);
        set(6, isDelete);
        set(7, updateTime);
    }
}
