/*
 * This file is generated by jOOQ.
*/
package com.distribution.pojo.tables.records;


import com.distribution.pojo.tables.ProductDetail;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 积分兑换产品列表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProductDetailRecord extends UpdatableRecordImpl<ProductDetailRecord> implements Record6<String, String, Integer, String, Long, Integer> {

    private static final long serialVersionUID = -1519433870;

    /**
     * Setter for <code>distribution.product_detail.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>distribution.product_detail.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>distribution.product_detail.prod_detail_name</code>. 产品名称
     */
    public void setProdDetailName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>distribution.product_detail.prod_detail_name</code>. 产品名称
     */
    public String getProdDetailName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>distribution.product_detail.prod_detail_buy_back</code>. 回购价
     */
    public void setProdDetailBuyBack(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>distribution.product_detail.prod_detail_buy_back</code>. 回购价
     */
    public Integer getProdDetailBuyBack() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>distribution.product_detail.prod_type_id</code>. 产品类型关联ID
     */
    public void setProdTypeId(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>distribution.product_detail.prod_type_id</code>. 产品类型关联ID
     */
    public String getProdTypeId() {
        return (String) get(3);
    }

    /**
     * Setter for <code>distribution.product_detail.prod_detail_value</code>. 产品积分数
     */
    public void setProdDetailValue(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>distribution.product_detail.prod_detail_value</code>. 产品积分数
     */
    public Long getProdDetailValue() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>distribution.product_detail.prod_detail_count</code>. 兑换次数
     */
    public void setProdDetailCount(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>distribution.product_detail.prod_detail_count</code>. 兑换次数
     */
    public Integer getProdDetailCount() {
        return (Integer) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<String, String, Integer, String, Long, Integer> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<String, String, Integer, String, Long, Integer> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return ProductDetail.PRODUCT_DETAIL.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return ProductDetail.PRODUCT_DETAIL.PROD_DETAIL_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return ProductDetail.PRODUCT_DETAIL.PROD_DETAIL_BUY_BACK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return ProductDetail.PRODUCT_DETAIL.PROD_TYPE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field5() {
        return ProductDetail.PRODUCT_DETAIL.PROD_DETAIL_VALUE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return ProductDetail.PRODUCT_DETAIL.PROD_DETAIL_COUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getProdDetailName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getProdDetailBuyBack();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getProdTypeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component5() {
        return getProdDetailValue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component6() {
        return getProdDetailCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getProdDetailName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getProdDetailBuyBack();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getProdTypeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value5() {
        return getProdDetailValue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getProdDetailCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductDetailRecord value1(String value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductDetailRecord value2(String value) {
        setProdDetailName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductDetailRecord value3(Integer value) {
        setProdDetailBuyBack(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductDetailRecord value4(String value) {
        setProdTypeId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductDetailRecord value5(Long value) {
        setProdDetailValue(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductDetailRecord value6(Integer value) {
        setProdDetailCount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductDetailRecord values(String value1, String value2, Integer value3, String value4, Long value5, Integer value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProductDetailRecord
     */
    public ProductDetailRecord() {
        super(ProductDetail.PRODUCT_DETAIL);
    }

    /**
     * Create a detached, initialised ProductDetailRecord
     */
    public ProductDetailRecord(String id, String prodDetailName, Integer prodDetailBuyBack, String prodTypeId, Long prodDetailValue, Integer prodDetailCount) {
        super(ProductDetail.PRODUCT_DETAIL);

        set(0, id);
        set(1, prodDetailName);
        set(2, prodDetailBuyBack);
        set(3, prodTypeId);
        set(4, prodDetailValue);
        set(5, prodDetailCount);
    }
}
