/*
 * This file is generated by jOOQ.
*/
package com.distribution.pojo.tables.records;


import com.distribution.pojo.tables.ScheduleJobLog;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * ??????
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ScheduleJobLogRecord extends UpdatableRecordImpl<ScheduleJobLogRecord> implements Record9<Long, Long, String, String, String, Boolean, String, Integer, Timestamp> {

    private static final long serialVersionUID = 726113217;

    /**
     * Setter for <code>distribution.schedule_job_log.log_id</code>. ????ID
     */
    public void setLogId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>distribution.schedule_job_log.log_id</code>. ????ID
     */
    public Long getLogId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>distribution.schedule_job_log.job_id</code>. ??ID

     */
    public void setJobId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>distribution.schedule_job_log.job_id</code>. ??ID

     */
    public Long getJobId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>distribution.schedule_job_log.bean_name</code>. spring bean ??
     */
    public void setBeanName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>distribution.schedule_job_log.bean_name</code>. spring bean ??
     */
    public String getBeanName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>distribution.schedule_job_log.method_name</code>. ???
     */
    public void setMethodName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>distribution.schedule_job_log.method_name</code>. ???
     */
    public String getMethodName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>distribution.schedule_job_log.params</code>. ??
     */
    public void setParams(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>distribution.schedule_job_log.params</code>. ??
     */
    public String getParams() {
        return (String) get(4);
    }

    /**
     * Setter for <code>distribution.schedule_job_log.status</code>. ????    0???    1???
     */
    public void setStatus(Boolean value) {
        set(5, value);
    }

    /**
     * Getter for <code>distribution.schedule_job_log.status</code>. ????    0???    1???
     */
    public Boolean getStatus() {
        return (Boolean) get(5);
    }

    /**
     * Setter for <code>distribution.schedule_job_log.error</code>. ????
     */
    public void setError(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>distribution.schedule_job_log.error</code>. ????
     */
    public String getError() {
        return (String) get(6);
    }

    /**
     * Setter for <code>distribution.schedule_job_log.times</code>. ??(?????)
     */
    public void setTimes(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>distribution.schedule_job_log.times</code>. ??(?????)
     */
    public Integer getTimes() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>distribution.schedule_job_log.create_time</code>. ????
     */
    public void setCreateTime(Timestamp value) {
        set(8, value);
    }

    /**
     * Getter for <code>distribution.schedule_job_log.create_time</code>. ????
     */
    public Timestamp getCreateTime() {
        return (Timestamp) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Long, Long, String, String, String, Boolean, String, Integer, Timestamp> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Long, Long, String, String, String, Boolean, String, Integer, Timestamp> valuesRow() {
        return (Row9) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return ScheduleJobLog.SCHEDULE_JOB_LOG.LOG_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return ScheduleJobLog.SCHEDULE_JOB_LOG.JOB_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return ScheduleJobLog.SCHEDULE_JOB_LOG.BEAN_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return ScheduleJobLog.SCHEDULE_JOB_LOG.METHOD_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return ScheduleJobLog.SCHEDULE_JOB_LOG.PARAMS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field6() {
        return ScheduleJobLog.SCHEDULE_JOB_LOG.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return ScheduleJobLog.SCHEDULE_JOB_LOG.ERROR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field8() {
        return ScheduleJobLog.SCHEDULE_JOB_LOG.TIMES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field9() {
        return ScheduleJobLog.SCHEDULE_JOB_LOG.CREATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getLogId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component2() {
        return getJobId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getBeanName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getMethodName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getParams();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component6() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getError();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component8() {
        return getTimes();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component9() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getLogId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getJobId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getBeanName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getMethodName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getParams();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value6() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getError();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value8() {
        return getTimes();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value9() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ScheduleJobLogRecord value1(Long value) {
        setLogId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ScheduleJobLogRecord value2(Long value) {
        setJobId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ScheduleJobLogRecord value3(String value) {
        setBeanName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ScheduleJobLogRecord value4(String value) {
        setMethodName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ScheduleJobLogRecord value5(String value) {
        setParams(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ScheduleJobLogRecord value6(Boolean value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ScheduleJobLogRecord value7(String value) {
        setError(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ScheduleJobLogRecord value8(Integer value) {
        setTimes(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ScheduleJobLogRecord value9(Timestamp value) {
        setCreateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ScheduleJobLogRecord values(Long value1, Long value2, String value3, String value4, String value5, Boolean value6, String value7, Integer value8, Timestamp value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ScheduleJobLogRecord
     */
    public ScheduleJobLogRecord() {
        super(ScheduleJobLog.SCHEDULE_JOB_LOG);
    }

    /**
     * Create a detached, initialised ScheduleJobLogRecord
     */
    public ScheduleJobLogRecord(Long logId, Long jobId, String beanName, String methodName, String params, Boolean status, String error, Integer times, Timestamp createTime) {
        super(ScheduleJobLog.SCHEDULE_JOB_LOG);

        set(0, logId);
        set(1, jobId);
        set(2, beanName);
        set(3, methodName);
        set(4, params);
        set(5, status);
        set(6, error);
        set(7, times);
        set(8, createTime);
    }
}
