/*
 * This file is generated by jOOQ.
*/
package com.distribution.pojo.tables;


import com.distribution.pojo.DistributionDev;
import com.distribution.pojo.Indexes;
import com.distribution.pojo.Keys;
import com.distribution.pojo.tables.records.DisProfiParamRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * 分润参数设置
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DisProfiParam extends TableImpl<DisProfiParamRecord> {

    private static final long serialVersionUID = 435465468;

    /**
     * The reference instance of <code>distribution_dev.dis_profi_param</code>
     */
    public static final DisProfiParam DIS_PROFI_PARAM = new DisProfiParam();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DisProfiParamRecord> getRecordType() {
        return DisProfiParamRecord.class;
    }

    /**
     * The column <code>distribution_dev.dis_profi_param.id</code>.
     */
    public final TableField<DisProfiParamRecord, String> ID = createField("id", org.jooq.impl.SQLDataType.VARCHAR(32).nullable(false), this, "");

    /**
     * The column <code>distribution_dev.dis_profi_param.dis_platform_id</code>. 平台id
     */
    public final TableField<DisProfiParamRecord, String> DIS_PLATFORM_ID = createField("dis_platform_id", org.jooq.impl.SQLDataType.VARCHAR(100), this, "平台id");

    /**
     * The column <code>distribution_dev.dis_profi_param.dis_pro_mode</code>. 分润模型，如 百分比和固定金额
     */
    public final TableField<DisProfiParamRecord, String> DIS_PRO_MODE = createField("dis_pro_mode", org.jooq.impl.SQLDataType.VARCHAR(100).nullable(false), this, "分润模型，如 百分比和固定金额");

    /**
     * The column <code>distribution_dev.dis_profi_param.dis_pro_type</code>. 分润类别，如上级发展下级分润 ，交易分润。。。。
     */
    public final TableField<DisProfiParamRecord, String> DIS_PRO_TYPE = createField("dis_pro_type", org.jooq.impl.SQLDataType.VARCHAR(100), this, "分润类别，如上级发展下级分润 ，交易分润。。。。");

    /**
     * The column <code>distribution_dev.dis_profi_param.dis_pro_value</code>. 分润值
     */
    public final TableField<DisProfiParamRecord, Double> DIS_PRO_VALUE = createField("dis_pro_value", org.jooq.impl.SQLDataType.DOUBLE, this, "分润值");

    /**
     * The column <code>distribution_dev.dis_profi_param.dis_pro_level</code>. 从下往上对应的级别关系
     */
    public final TableField<DisProfiParamRecord, String> DIS_PRO_LEVEL = createField("dis_pro_level", org.jooq.impl.SQLDataType.VARCHAR(100), this, "从下往上对应的级别关系");

    /**
     * The column <code>distribution_dev.dis_profi_param.dis_user_type</code>. 会员类型（0:非会员 1：会员）
     */
    public final TableField<DisProfiParamRecord, String> DIS_USER_TYPE = createField("dis_user_type", org.jooq.impl.SQLDataType.VARCHAR(100), this, "会员类型（0:非会员 1：会员）");

    /**
     * The column <code>distribution_dev.dis_profi_param.is_delete</code>.
     */
    public final TableField<DisProfiParamRecord, String> IS_DELETE = createField("is_delete", org.jooq.impl.SQLDataType.VARCHAR(1), this, "");

    /**
     * The column <code>distribution_dev.dis_profi_param.update_time</code>.
     */
    public final TableField<DisProfiParamRecord, String> UPDATE_TIME = createField("update_time", org.jooq.impl.SQLDataType.VARCHAR(20), this, "");

    /**
     * The column <code>distribution_dev.dis_profi_param.add_time</code>.
     */
    public final TableField<DisProfiParamRecord, String> ADD_TIME = createField("add_time", org.jooq.impl.SQLDataType.VARCHAR(20), this, "");

    /**
     * Create a <code>distribution_dev.dis_profi_param</code> table reference
     */
    public DisProfiParam() {
        this(DSL.name("dis_profi_param"), null);
    }

    /**
     * Create an aliased <code>distribution_dev.dis_profi_param</code> table reference
     */
    public DisProfiParam(String alias) {
        this(DSL.name(alias), DIS_PROFI_PARAM);
    }

    /**
     * Create an aliased <code>distribution_dev.dis_profi_param</code> table reference
     */
    public DisProfiParam(Name alias) {
        this(alias, DIS_PROFI_PARAM);
    }

    private DisProfiParam(Name alias, Table<DisProfiParamRecord> aliased) {
        this(alias, aliased, null);
    }

    private DisProfiParam(Name alias, Table<DisProfiParamRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "分润参数设置");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DistributionDev.DISTRIBUTION_DEV;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.DIS_PROFI_PARAM_DIS_PROFI_PARAM_ID_UINDEX, Indexes.DIS_PROFI_PARAM_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<DisProfiParamRecord> getPrimaryKey() {
        return Keys.KEY_DIS_PROFI_PARAM_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<DisProfiParamRecord>> getKeys() {
        return Arrays.<UniqueKey<DisProfiParamRecord>>asList(Keys.KEY_DIS_PROFI_PARAM_PRIMARY, Keys.KEY_DIS_PROFI_PARAM_DIS_PROFI_PARAM_ID_UINDEX);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DisProfiParam as(String alias) {
        return new DisProfiParam(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DisProfiParam as(Name alias) {
        return new DisProfiParam(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public DisProfiParam rename(String name) {
        return new DisProfiParam(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public DisProfiParam rename(Name name) {
        return new DisProfiParam(name, null);
    }
}
