/*
 * This file is generated by jOOQ.
*/
package com.distribution.pojo.tables;


import com.distribution.pojo.Distribution;
import com.distribution.pojo.Indexes;
import com.distribution.pojo.Keys;
import com.distribution.pojo.tables.records.MobileMessageRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * 发送短信信息表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MobileMessage extends TableImpl<MobileMessageRecord> {

    private static final long serialVersionUID = -2055836189;

    /**
     * The reference instance of <code>distribution.mobile_message</code>
     */
    public static final MobileMessage MOBILE_MESSAGE = new MobileMessage();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MobileMessageRecord> getRecordType() {
        return MobileMessageRecord.class;
    }

    /**
     * The column <code>distribution.mobile_message.id</code>.
     */
    public final TableField<MobileMessageRecord, String> ID = createField("id", org.jooq.impl.SQLDataType.VARCHAR(32).nullable(false), this, "");

    /**
     * The column <code>distribution.mobile_message.mobile</code>.
     */
    public final TableField<MobileMessageRecord, String> MOBILE = createField("mobile", org.jooq.impl.SQLDataType.VARCHAR(12), this, "");

    /**
     * The column <code>distribution.mobile_message.code</code>.
     */
    public final TableField<MobileMessageRecord, String> CODE = createField("code", org.jooq.impl.SQLDataType.VARCHAR(20), this, "");

    /**
     * The column <code>distribution.mobile_message.send_time</code>.
     */
    public final TableField<MobileMessageRecord, String> SEND_TIME = createField("send_time", org.jooq.impl.SQLDataType.VARCHAR(20), this, "");

    /**
     * The column <code>distribution.mobile_message.count</code>.
     */
    public final TableField<MobileMessageRecord, Integer> COUNT = createField("count", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>distribution.mobile_message.add_time</code>.
     */
    public final TableField<MobileMessageRecord, String> ADD_TIME = createField("add_time", org.jooq.impl.SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>distribution.mobile_message.is_delete</code>.
     */
    public final TableField<MobileMessageRecord, String> IS_DELETE = createField("is_delete", org.jooq.impl.SQLDataType.VARCHAR(20), this, "");

    /**
     * The column <code>distribution.mobile_message.update_time</code>.
     */
    public final TableField<MobileMessageRecord, String> UPDATE_TIME = createField("update_time", org.jooq.impl.SQLDataType.VARCHAR(20), this, "");

    /**
     * Create a <code>distribution.mobile_message</code> table reference
     */
    public MobileMessage() {
        this(DSL.name("mobile_message"), null);
    }

    /**
     * Create an aliased <code>distribution.mobile_message</code> table reference
     */
    public MobileMessage(String alias) {
        this(DSL.name(alias), MOBILE_MESSAGE);
    }

    /**
     * Create an aliased <code>distribution.mobile_message</code> table reference
     */
    public MobileMessage(Name alias) {
        this(alias, MOBILE_MESSAGE);
    }

    private MobileMessage(Name alias, Table<MobileMessageRecord> aliased) {
        this(alias, aliased, null);
    }

    private MobileMessage(Name alias, Table<MobileMessageRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "发送短信信息表");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Distribution.DISTRIBUTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.MOBILE_MESSAGE_MOBILE_MESSAGE_ID_UINDEX, Indexes.MOBILE_MESSAGE_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<MobileMessageRecord> getPrimaryKey() {
        return Keys.KEY_MOBILE_MESSAGE_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<MobileMessageRecord>> getKeys() {
        return Arrays.<UniqueKey<MobileMessageRecord>>asList(Keys.KEY_MOBILE_MESSAGE_PRIMARY, Keys.KEY_MOBILE_MESSAGE_MOBILE_MESSAGE_ID_UINDEX);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MobileMessage as(String alias) {
        return new MobileMessage(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MobileMessage as(Name alias) {
        return new MobileMessage(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public MobileMessage rename(String name) {
        return new MobileMessage(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public MobileMessage rename(Name name) {
        return new MobileMessage(name, null);
    }
}
